(function(){function d(a){throw a;}var h=void 0,i=!0,l=null,n=!1;function aa(){return function(a){return a}}function o(){return function(){}}function p(a){return function(b){this[a]=b}}function r(a){return function(){return this[a]}}function t(a){return function(){return a}}var w,x=x||{};x.global=this;x.$z=n;x.dN="en";x.tP=function(a){x.HG(a)};x.DP=function(a){x.$z||(a=a||"",d(Error("Importing test-only code into non-debug environment"+a?": "+a:".")))};
x.HG=function(a,b,c){a=a.split(".");c=c||x.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&x.to(b)?c[e]=b:c=c[e]?c[e]:c[e]={}};x.QK=function(){for(var a=["window","event"],b=x.global,c;c=a.shift();)if(x.kL(b[c]))b=b[c];else return l;return b};x.MO=function(a,b){var c=b||x.global,e;for(e in a)c[e]=a[e]};x.EN=o();x.OM=i;x.yP=o();x.RN="";x.oI=o();x.RO=aa();x.ma=function(){d(Error("unimplemented abstract method"))};
x.FN=function(a){a.zO=function(){return a.gL||(a.gL=new a)}};
x.tj=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};x.to=function(a){return a!==h};x.ZO=function(a){return a===l};x.kL=function(a){return a!=l};x.isArray=function(a){return"array"==x.tj(a)};x.Fe=function(a){var b=x.tj(a);return"array"==b||"object"==b&&"number"==typeof a.length};x.XO=function(a){return x.Qm(a)&&"function"==typeof a.getFullYear};x.Gc=function(a){return"string"==typeof a};x.iL=function(a){return"boolean"==typeof a};x.GH=function(a){return"number"==typeof a};
x.Jx=function(a){return"function"==x.tj(a)};x.Qm=function(a){var b=typeof a;return"object"==b&&a!=l||"function"==b};x.Am=function(a){return a[x.Fv]||(a[x.Fv]=++x.hM)};x.SL=function(a){"removeAttribute"in a&&a.removeAttribute(x.Fv);try{delete a[x.Fv]}catch(b){}};x.Fv="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36);x.hM=0;x.wO=x.Am;x.wP=x.SL;x.YJ=function(a){var b=x.tj(a);if("object"==b||"array"==b){if(a.ia)return a.ia();var b="array"==b?[]:{},c;for(c in a)b[c]=x.YJ(a[c]);return b}return a};
x.TJ=function(a,b,c){return a.call.apply(a.bind,arguments)};x.SJ=function(a,b,c){a||d(Error());if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};x.bind=function(a,b,c){x.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?x.TJ:x.SJ;return x.bind.apply(l,arguments)};
x.xI=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};x.hP=function(a,b){for(var c in b)a[c]=b[c]};x.now=Date.now||function(){return+new Date};
x.LO=function(a){if(x.global.execScript)x.global.execScript(a,"JavaScript");else if(x.global.eval)if(x.Ow==l&&(x.global.eval("var _et_ = 1;"),"undefined"!=typeof x.global._et_?(delete x.global._et_,x.Ow=i):x.Ow=n),x.Ow)x.global.eval(a);else{var b=x.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=n;c.appendChild(b.createTextNode(a));b.body.appendChild(c);b.body.removeChild(c)}else d(Error("goog.globalEval not available"))};x.Ow=l;
x.vO=function(a,b){function c(a){return x.fG[a]||a}var e;e=x.fG?"BY_WHOLE"==x.gK?c:function(a){for(var a=a.split("-"),b=[],e=0;e<a.length;e++)b.push(c(a[e]));return b.join("-")}:aa();return b?a+"-"+e(b):e(a)};x.zP=function(a,b){x.fG=a;x.gK=b};x.CO=function(a,b){var c=b||{},e;for(e in c)var f=(""+c[e]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f);return a};x.vg=function(a,b){x.HG(a,b,h)};x.O=function(a,b,c){a[b]=c};
x.f=function(a,b){function c(){}c.prototype=b.prototype;a.b=b.prototype;a.prototype=new c;a.prototype.constructor=a};x.QN=function(a,b,c){var e=arguments.callee.caller;if(e.b)return e.b.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),g=n,j=a.constructor;j;j=j.b&&j.b.constructor)if(j.prototype[b]===e)g=i;else if(g)return j.prototype[b].apply(a,f);if(a[b]===e)return a.constructor.prototype[b].apply(a,f);d(Error("goog.base called from a method of one name to a method of a different name"))};
x.scope=function(a){a.call(x.global)};x.debug={};function ba(a){this.stack=Error().stack||"";a&&(this.message=""+a)}x.f(ba,Error);ba.prototype.name="CustomError";x.N={};x.N.cM=function(a){return 0==a.lastIndexOf("/",0)};x.N.xK=function(a){var b=a.length-1;return 0<=b&&a.indexOf("/",b)==b};x.N.$N=function(a,b){return 0==x.N.NF(b,a.substr(0,b.length))};x.N.ZN=function(a,b){return 0==x.N.NF(b,a.substr(a.length-b.length,b.length))};x.N.dM=function(a,b){for(var c=1;c<arguments.length;c++)var e=(""+arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a};x.N.eO=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};x.N.Xh=function(a){return/^[\s\xa0]*$/.test(a)};
x.N.YO=function(a){return x.N.Xh(x.N.uL(a))};x.N.WO=function(a){return!/[^\t\n\r ]/.test(a)};x.N.UO=function(a){return!/[^a-zA-Z]/.test(a)};x.N.$O=function(a){return!/[^0-9]/.test(a)};x.N.VO=function(a){return!/[^a-zA-Z0-9]/.test(a)};x.N.bP=function(a){return" "==a};x.N.cP=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};x.N.IP=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};x.N.YN=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
x.N.lP=function(a){return a.replace(/\xa0|\s/g," ")};x.N.kP=function(a){return a.replace(/\xa0|[ \t]+/g," ")};x.N.dO=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};x.N.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};x.N.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};x.N.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};x.N.NF=function(a,b){var c=(""+a).toLowerCase(),e=(""+b).toLowerCase();return c<e?-1:c==e?0:1};x.N.qI=/(\.\d+)|(\d+)|(\D+)/g;
x.N.mP=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(x.N.qI),e=b.toLowerCase().match(x.N.qI),f=Math.min(c.length,e.length),g=0;g<f;g++){var j=c[g],k=e[g];if(j!=k)return c=parseInt(j,10),!isNaN(c)&&(e=parseInt(k,10),!isNaN(e)&&c-e)?c-e:j<k?-1:1}return c.length!=e.length?c.length-e.length:a<b?-1:1};x.N.wK=/^[a-zA-Z0-9\-_.!~*'()]*$/;x.N.Wr=function(a){a=""+a;return!x.N.wK.test(a)?encodeURIComponent(a):a};
x.N.Gz=function(a){return decodeURIComponent(a.replace(/\+/g," "))};x.N.zL=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};x.N.jH=function(a){if(!x.N.OJ.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(x.N.PJ,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(x.N.tL,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(x.N.aL,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(x.N.LL,"&quot;"));return a};x.N.PJ=/&/g;x.N.tL=/</g;x.N.aL=/>/g;x.N.LL=/\"/g;x.N.OJ=/[&<>\"]/;
x.N.rJ=function(a){return x.N.contains(a,"&")?"document"in x.global?x.N.iM(a):x.N.jM(a):a};x.N.iM=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(x.N.JJ,function(a,f){var g=b[a];if(g)return g;if("#"==f.charAt(0)){var j=Number("0"+f.substr(1));isNaN(j)||(g=String.fromCharCode(j))}g||(c.innerHTML=a+" ",g=c.firstChild.nodeValue.slice(0,-1));return b[a]=g})};
x.N.jM=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var e=Number("0"+c.substr(1));if(!isNaN(e))return String.fromCharCode(e)}return a}})};x.N.JJ=/&([^;\s<&]+);?/g;x.N.VP=function(a,b){return x.N.zL(a.replace(/  /g," &#160;"),b)};
x.N.JP=function(a,b){for(var c=b.length,e=0;e<c;e++){var f=1==c?b:b.charAt(e);if(a.charAt(0)==f&&a.charAt(a.length-1)==f)return a.substring(1,a.length-1)}return a};x.N.truncate=function(a,b,c){c&&(a=x.N.rJ(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=x.N.jH(a));return a};
x.N.PP=function(a,b,c,e){c&&(a=x.N.rJ(a));if(e&&a.length>b)e>b&&(e=b),a=a.substring(0,b-e)+"..."+a.substring(a.length-e);else if(a.length>b)var e=Math.floor(b/2),f=a.length-e,a=a.substring(0,e+b%2)+"..."+a.substring(f);c&&(a=x.N.jH(a));return a};x.N.FE={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};x.N.Sx={"'":"\\'"};
x.N.quote=function(a){a=""+a;if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var e=a.charAt(c),f=e.charCodeAt(0);b[c+1]=x.N.FE[e]||(31<f&&127>f?e:x.N.DG(e))}b.push('"');return b.join("")};x.N.nO=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=x.N.DG(a.charAt(c));return b.join("")};
x.N.DG=function(a){if(a in x.N.Sx)return x.N.Sx[a];if(a in x.N.FE)return x.N.Sx[a]=x.N.FE[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return x.N.Sx[a]=b};x.N.MP=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=i;return b};x.N.contains=function(a,b){return-1!=a.indexOf(b)};x.N.gO=function(a,b){return a&&b?a.split(b).length-1:0};
x.N.By=function(a,b,c){var e=a;0<=b&&b<a.length&&0<c&&(e=a.substr(0,b)+a.substr(b+c,a.length-b-c));return e};x.N.remove=function(a,b){var c=RegExp(x.N.II(b),"");return a.replace(c,"")};x.N.LI=function(a,b){var c=RegExp(x.N.II(b),"g");return a.replace(c,"")};x.N.II=function(a){return(""+a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};x.N.repeat=function(a,b){return Array(b+1).join(a)};
x.N.oP=function(a,b,c){a=x.to(c)?a.toFixed(c):""+a;c=a.indexOf(".");-1==c&&(c=a.length);return x.N.repeat("0",Math.max(0,b-c))+a};x.N.uL=function(a){return a==l?"":""+a};x.N.UJ=function(a){return Array.prototype.join.call(arguments,"")};x.N.bH=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^x.now()).toString(36)};
x.N.UF=function(a,b){for(var c=0,e=x.N.trim(""+a).split("."),f=x.N.trim(""+b).split("."),g=Math.max(e.length,f.length),j=0;0==c&&j<g;j++){var k=e[j]||"",m=f[j]||"",q=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var u=q.exec(k)||["","",""],v=s.exec(m)||["","",""];if(0==u[0].length&&0==v[0].length)break;c=x.N.RA(0==u[1].length?0:parseInt(u[1],10),0==v[1].length?0:parseInt(v[1],10))||x.N.RA(0==u[2].length,0==v[2].length)||x.N.RA(u[2],v[2])}while(0==c)}return c};
x.N.RA=function(a,b){return a<b?-1:a>b?1:0};x.N.IJ=4294967296;x.N.PO=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=x.N.IJ;return b};x.N.lM=2147483648*Math.random()|0;x.N.iO=function(){return"goog_"+x.N.lM++};x.N.NP=function(a){var b=Number(a);return 0==b&&x.N.Xh(a)?NaN:b};x.N.nJ={};x.N.LP=function(a){return x.N.nJ[a]||(x.N.nJ[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};x.N.oJ={};
x.N.OP=function(a){return x.N.oJ[a]||(x.N.oJ[a]=(""+a).replace(/([A-Z])/g,"-$1").toLowerCase())};x.Nc={};x.Nc.Ek=x.$z;function da(a,b){b.unshift(a);ba.call(this,x.N.dM.apply(l,b));b.shift()}x.f(da,ba);da.prototype.name="AssertionError";x.Nc.fm=function(a,b,c,e){var f="Assertion failed";if(c)var f=f+(": "+c),g=e;else a&&(f+=": "+a,g=b);d(new da(""+f,g||[]))};x.Nc.assert=function(a,b,c){x.Nc.Ek&&!a&&x.Nc.fm("",l,b,Array.prototype.slice.call(arguments,2));return a};x.Nc.pO=function(a,b){x.Nc.Ek&&d(new da("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};
x.Nc.NN=function(a,b,c){x.Nc.Ek&&!x.GH(a)&&x.Nc.fm("Expected number but got %s: %s.",[x.tj(a),a],b,Array.prototype.slice.call(arguments,2));return a};x.Nc.PN=function(a,b,c){x.Nc.Ek&&!x.Gc(a)&&x.Nc.fm("Expected string but got %s: %s.",[x.tj(a),a],b,Array.prototype.slice.call(arguments,2));return a};x.Nc.LN=function(a,b,c){x.Nc.Ek&&!x.Jx(a)&&x.Nc.fm("Expected function but got %s: %s.",[x.tj(a),a],b,Array.prototype.slice.call(arguments,2));return a};
x.Nc.ON=function(a,b,c){x.Nc.Ek&&!x.Qm(a)&&x.Nc.fm("Expected object but got %s: %s.",[x.tj(a),a],b,Array.prototype.slice.call(arguments,2));return a};x.Nc.JN=function(a,b,c){x.Nc.Ek&&!x.isArray(a)&&x.Nc.fm("Expected array but got %s: %s.",[x.tj(a),a],b,Array.prototype.slice.call(arguments,2));return a};x.Nc.KN=function(a,b,c){x.Nc.Ek&&!x.iL(a)&&x.Nc.fm("Expected boolean but got %s: %s.",[x.tj(a),a],b,Array.prototype.slice.call(arguments,2));return a};
x.Nc.MN=function(a,b,c,e){x.Nc.Ek&&!(a instanceof b)&&x.Nc.fm("instanceof check failed.",l,c,Array.prototype.slice.call(arguments,3))};x.Q={};x.yn=i;x.Q.pP=function(a){return a[a.length-1]};x.Q.Ad=Array.prototype;x.Q.indexOf=x.yn&&x.Q.Ad.indexOf?function(a,b,c){return x.Q.Ad.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(x.Gc(a))return!x.Gc(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
x.Q.lastIndexOf=x.yn&&x.Q.Ad.lastIndexOf?function(a,b,c){return x.Q.Ad.lastIndexOf.call(a,b,c==l?a.length-1:c)}:function(a,b,c){c=c==l?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(x.Gc(a))return!x.Gc(b)||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};x.Q.forEach=x.yn&&x.Q.Ad.forEach?function(a,b,c){x.Q.Ad.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=x.Gc(a)?a.split(""):a,g=0;g<e;g++)g in f&&b.call(c,f[g],g,a)};
x.Q.BK=function(a,b){for(var c=a.length,e=x.Gc(a)?a.split(""):a,c=c-1;0<=c;--c)c in e&&b.call(h,e[c],c,a)};x.Q.filter=x.yn&&x.Q.Ad.filter?function(a,b,c){return x.Q.Ad.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],g=0,j=x.Gc(a)?a.split(""):a,k=0;k<e;k++)if(k in j){var m=j[k];b.call(c,m,k,a)&&(f[g++]=m)}return f};
x.Q.map=x.yn&&x.Q.Ad.map?function(a,b,c){return x.Q.Ad.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),g=x.Gc(a)?a.split(""):a,j=0;j<e;j++)j in g&&(f[j]=b.call(c,g[j],j,a));return f};x.Q.reduce=function(a,b,c,e){if(a.reduce)return e?a.reduce(x.bind(b,e),c):a.reduce(b,c);var f=c;x.Q.forEach(a,function(c,j){f=b.call(e,f,c,j,a)});return f};
x.Q.reduceRight=function(a,b,c,e){if(a.reduceRight)return e?a.reduceRight(x.bind(b,e),c):a.reduceRight(b,c);var f=c;x.Q.BK(a,function(c,j){f=b.call(e,f,c,j,a)});return f};x.Q.some=x.yn&&x.Q.Ad.some?function(a,b,c){return x.Q.Ad.some.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=x.Gc(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&b.call(c,f[g],g,a))return i;return n};
x.Q.every=x.yn&&x.Q.Ad.every?function(a,b,c){return x.Q.Ad.every.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=x.Gc(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&!b.call(c,f[g],g,a))return n;return i};x.Q.find=function(a,b,c){b=x.Q.LG(a,b,c);return 0>b?l:x.Gc(a)?a.charAt(b):a[b]};x.Q.LG=function(a,b,c){for(var e=a.length,f=x.Gc(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&b.call(c,f[g],g,a))return g;return-1};x.Q.qO=function(a,b,c){b=x.Q.yK(a,b,c);return 0>b?l:x.Gc(a)?a.charAt(b):a[b]};
x.Q.yK=function(a,b,c){for(var e=a.length,f=x.Gc(a)?a.split(""):a,e=e-1;0<=e;e--)if(e in f&&b.call(c,f[e],e,a))return e;return-1};x.Q.contains=function(a,b){return 0<=x.Q.indexOf(a,b)};x.Q.Xh=function(a){return 0==a.length};x.Q.clear=function(a){if(!x.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};x.Q.SO=function(a,b){x.Q.contains(a,b)||a.push(b)};x.Q.rH=function(a,b,c){x.Q.splice(a,c,0,b)};x.Q.TO=function(a,b,c){x.xI(x.Q.splice,a,c,0).apply(l,b)};
x.Q.insertBefore=function(a,b,c){var e;2==arguments.length||0>(e=x.Q.indexOf(a,c))?a.push(b):x.Q.rH(a,b,e)};x.Q.remove=function(a,b){var c=x.Q.indexOf(a,b),e;(e=0<=c)&&x.Q.By(a,c);return e};x.Q.By=function(a,b){return 1==x.Q.Ad.splice.call(a,b,1).length};x.Q.xP=function(a,b,c){b=x.Q.LG(a,b,c);return 0<=b?(x.Q.By(a,b),i):n};x.Q.concat=function(a){return x.Q.Ad.concat.apply(x.Q.Ad,arguments)};x.Q.ia=function(a){if(x.isArray(a))return x.Q.concat(a);for(var b=[],c=0,e=a.length;c<e;c++)b[c]=a[c];return b};
x.Q.XE=function(a){return x.isArray(a)?x.Q.concat(a):x.Q.ia(a)};x.Q.extend=function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c],f;if(x.isArray(e)||(f=x.Fe(e))&&e.hasOwnProperty("callee"))a.push.apply(a,e);else if(f)for(var g=a.length,j=e.length,k=0;k<j;k++)a[g+k]=e[k];else a.push(e)}};x.Q.splice=function(a,b,c,e){return x.Q.Ad.splice.apply(a,x.Q.slice(arguments,1))};x.Q.slice=function(a,b,c){return 2>=arguments.length?x.Q.Ad.slice.call(a,b):x.Q.Ad.slice.call(a,b,c)};
x.Q.vP=function(a,b){for(var c=b||a,e={},f=0,g=0;g<a.length;){var j=a[g++],k=x.Qm(j)?"o"+x.Am(j):(typeof j).charAt(0)+j;Object.prototype.hasOwnProperty.call(e,k)||(e[k]=i,c[f++]=j)}c.length=f};x.Q.FF=function(a,b,c){return x.Q.GF(a,c||x.Q.Sn,n,b)};x.Q.UN=function(a,b,c){return x.Q.GF(a,b,i,h,c)};x.Q.GF=function(a,b,c,e,f){for(var g=0,j=a.length,k;g<j;){var m=g+j>>1,q;q=c?b.call(f,a[m],m,a):b(e,a[m]);0<q?g=m+1:(j=m,k=!q)}return k?g:~g};x.Q.sort=function(a,b){x.Q.Ad.sort.call(a,b||x.Q.Sn)};
x.Q.HP=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var e=b||x.Q.Sn;x.Q.sort(a,function(a,b){return e(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value};x.Q.GP=function(a,b,c){var e=c||x.Q.Sn;x.Q.sort(a,function(a,c){return e(a[b],c[b])})};x.Q.aP=function(a,b,c){for(var b=b||x.Q.Sn,e=1;e<a.length;e++){var f=b(a[e-1],a[e]);if(0<f||0==f&&c)return n}return i};
x.Q.FB=function(a,b,c){if(!x.Fe(a)||!x.Fe(b)||a.length!=b.length)return n;for(var e=a.length,c=c||x.Q.hK,f=0;f<e;f++)if(!c(a[f],b[f]))return n;return i};x.Q.ZJ=function(a,b,c){return x.Q.FB(a,b,c)};x.Q.fO=function(a,b,c){for(var c=c||x.Q.Sn,e=Math.min(a.length,b.length),f=0;f<e;f++){var g=c(a[f],b[f]);if(0!=g)return g}return x.Q.Sn(a.length,b.length)};x.Q.Sn=function(a,b){return a>b?1:a<b?-1:0};x.Q.hK=function(a,b){return a===b};
x.Q.SN=function(a,b,c){c=x.Q.FF(a,b,c);return 0>c?(x.Q.rH(a,b,-(c+1)),i):n};x.Q.TN=function(a,b,c){b=x.Q.FF(a,b,c);return 0<=b?x.Q.By(a,b):n};x.Q.VN=function(a,b){for(var c={},e=0;e<a.length;e++){var f=a[e],g=b(f,e,a);x.to(g)&&(c[g]||(c[g]=[])).push(f)}return c};x.Q.repeat=function(a,b){for(var c=[],e=0;e<b;e++)c[e]=a;return c};x.Q.AK=function(a){for(var b=[],c=0;c<arguments.length;c++){var e=arguments[c];x.isArray(e)?b.push.apply(b,x.Q.AK.apply(l,e)):b.push(e)}return b};
x.Q.rotate=function(a,b){a.length&&(b%=a.length,0<b?x.Q.Ad.unshift.apply(a,a.splice(-b,b)):0>b&&x.Q.Ad.push.apply(a,a.splice(0,-b)));return a};x.Q.WP=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var e=[],f=0;f<arguments.length;f++){var g=arguments[f];if(c>=g.length)return b;e.push(g[c])}b.push(e)}};x.Q.FP=function(a,b){for(var c=b||Math.random,e=a.length-1;0<e;e--){var f=Math.floor(c()*(e+1)),g=a[e];a[e]=a[f];a[f]=g}};x.debug.Ce={};x.debug.QM=o();x.debug.Ce.vr=[];x.debug.Ce.tD=[];x.debug.Ce.dI=n;x.debug.Ce.JI=function(a){x.debug.Ce.vr[x.debug.Ce.vr.length]=a;if(x.debug.Ce.dI)for(var b=x.debug.Ce.tD,c=0;c<b.length;c++)a(x.bind(b[c].rM,b[c]))};x.debug.Ce.iP=function(a){x.debug.Ce.dI=i;for(var b=x.bind(a.rM,a),c=0;c<x.debug.Ce.vr.length;c++)x.debug.Ce.vr[c](b);x.debug.Ce.tD.push(a)};x.debug.Ce.RP=function(a){for(var b=x.debug.Ce.tD,a=x.bind(a.TP,a),c=0;c<x.debug.Ce.vr.length;c++)x.debug.Ce.vr[c](a);b.length--};x.debug.mO={EI:aa()};x.userAgent={};x.userAgent.oF=n;x.userAgent.nF=n;x.userAgent.sF=n;x.userAgent.Yz=n;x.userAgent.rF=n;x.userAgent.CJ=n;x.userAgent.Gp=x.userAgent.oF||x.userAgent.nF||x.userAgent.Yz||x.userAgent.sF||x.userAgent.rF;x.userAgent.eH=function(){return x.global.navigator?x.global.navigator.userAgent:l};x.userAgent.hx=function(){return x.global.navigator};
x.userAgent.fL=function(){x.userAgent.bt=n;x.userAgent.nG=n;x.userAgent.Gw=n;x.userAgent.oG=n;x.userAgent.mG=n;var a;if(!x.userAgent.Gp&&(a=x.userAgent.eH())){var b=x.userAgent.hx();x.userAgent.bt=0==a.indexOf("Opera");x.userAgent.nG=!x.userAgent.bt&&-1!=a.indexOf("MSIE");x.userAgent.Gw=!x.userAgent.bt&&-1!=a.indexOf("WebKit");x.userAgent.oG=x.userAgent.Gw&&-1!=a.indexOf("Mobile");x.userAgent.mG=!x.userAgent.bt&&!x.userAgent.Gw&&"Gecko"==b.product}};x.userAgent.Gp||x.userAgent.fL();
x.userAgent.aA=x.userAgent.Gp?x.userAgent.rF:x.userAgent.bt;x.userAgent.vj=x.userAgent.Gp?x.userAgent.oF:x.userAgent.nG;x.userAgent.Dv=x.userAgent.Gp?x.userAgent.nF:x.userAgent.mG;x.userAgent.Pl=x.userAgent.Gp?x.userAgent.sF||x.userAgent.Yz:x.userAgent.Gw;x.userAgent.iN=x.userAgent.Yz||x.userAgent.oG;x.userAgent.rN=x.userAgent.Pl;x.userAgent.oK=function(){var a=x.userAgent.hx();return a&&a.platform||""};x.userAgent.bA=x.userAgent.oK();x.userAgent.qF=n;x.userAgent.tF=n;x.userAgent.pF=n;
x.userAgent.uF=n;x.userAgent.ns=x.userAgent.qF||x.userAgent.tF||x.userAgent.pF||x.userAgent.uF;x.userAgent.eL=function(){x.userAgent.lK=x.N.contains(x.userAgent.bA,"Mac");x.userAgent.mK=x.N.contains(x.userAgent.bA,"Win");x.userAgent.kK=x.N.contains(x.userAgent.bA,"Linux");x.userAgent.nK=!!x.userAgent.hx()&&x.N.contains(x.userAgent.hx().appVersion||"","X11")};x.userAgent.ns||x.userAgent.eL();x.userAgent.fN=x.userAgent.ns?x.userAgent.qF:x.userAgent.lK;x.userAgent.CN=x.userAgent.ns?x.userAgent.tF:x.userAgent.mK;
x.userAgent.bN=x.userAgent.ns?x.userAgent.pF:x.userAgent.kK;x.userAgent.DN=x.userAgent.ns?x.userAgent.uF:x.userAgent.nK;x.userAgent.pK=function(){var a="",b;x.userAgent.aA&&x.global.opera?(a=x.global.opera.version,a="function"==typeof a?a():a):(x.userAgent.Dv?b=/rv\:([^\);]+)(\)|;)/:x.userAgent.vj?b=/MSIE\s+([^\);]+)(\)|;)/:x.userAgent.Pl&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(x.userAgent.eH()))?a[1]:""));return x.userAgent.vj&&(b=x.userAgent.IK(),b>parseFloat(a))?""+b:a};
x.userAgent.IK=function(){var a=x.global.document;return a?a.documentMode:h};x.userAgent.VERSION=x.userAgent.pK();x.userAgent.ZJ=function(a,b){return x.N.UF(a,b)};x.userAgent.QH={};x.userAgent.Ao=function(a){return x.userAgent.CJ||x.userAgent.QH[a]||(x.userAgent.QH[a]=0<=x.N.UF(x.userAgent.VERSION,a))};x.userAgent.xH={};x.userAgent.wH=function(){return x.userAgent.xH[9]||(x.userAgent.xH[9]=x.userAgent.vj&&!!document.documentMode&&9<=document.documentMode)};x.r={};!x.userAgent.vj||x.userAgent.wH();var ea=!x.userAgent.vj||x.userAgent.wH(),fa=x.userAgent.vj&&!x.userAgent.Ao("8");!x.userAgent.Pl||x.userAgent.Ao("528");x.userAgent.Dv&&x.userAgent.Ao("1.9b")||x.userAgent.vj&&x.userAgent.Ao("8")||x.userAgent.aA&&x.userAgent.Ao("9.5")||x.userAgent.Pl&&x.userAgent.Ao("528");!x.userAgent.Dv||x.userAgent.Ao("8");x.qK={};x.qK.XM=o();function ga(){}ga.prototype.sG=n;ga.prototype.Ii=function(){this.sG||(this.sG=i,this.em())};ga.prototype.em=function(){this.iK&&x.rG.apply(l,this.iK)};x.Ii=function(a){a&&"function"==typeof a.Ii&&a.Ii()};x.rG=function(a){for(var b=0,c=arguments.length;b<c;++b){var e=arguments[b];x.Fe(e)?x.rG.apply(l,e):x.Ii(e)}};function ha(a,b){this.type=a;this.currentTarget=this.target=b}x.f(ha,ga);w=ha.prototype;w.em=function(){delete this.type;delete this.target;delete this.currentTarget};w.ep=n;w.Ju=i;w.stopPropagation=function(){this.ep=i};w.preventDefault=function(){this.Ju=n};ha.stopPropagation=function(a){a.stopPropagation()};ha.preventDefault=function(a){a.preventDefault()};var y={Zz:"click",GM:"dblclick",xn:"mousedown",Hp:"mouseup",zh:"mouseover",yh:"mouseout",xh:"mousemove",uN:"selectstart",$M:"keypress",ZM:"keydown",aN:"keyup",zM:"blur",SM:"focus",HM:"deactivate",TM:x.userAgent.vj?"focusin":"DOMFocusIn",UM:x.userAgent.vj?"focusout":"DOMFocusOut",BM:"change",tN:"select",vN:"submit",YM:"input",pN:"propertychange",LM:"dragstart",IM:"dragenter",KM:"dragover",JM:"dragleave",NM:"drop",zN:"touchstart",yN:"touchmove",xN:"touchend",wN:"touchcancel",DM:"contextmenu",PM:"error",
WM:"help",cN:"load",eN:"losecapture",qN:"readystatechange",Ev:"resize",sN:"scroll",BN:"unload",VM:"hashchange",lN:"pagehide",mN:"pageshow",oN:"popstate",EM:"copy",nN:"paste",FM:"cut",wM:"beforecopy",xM:"beforecut",yM:"beforepaste",gN:"message",CM:"connect",AN:x.userAgent.Pl?"webkitTransitionEnd":x.userAgent.aA?"oTransitionEnd":"transitionend"};x.gp={};x.gp.object=function(a,b){return b};x.gp.CE=function(a){x.gp.CE[" "](a);return a};x.gp.CE[" "]=x.oI;x.gp.VJ=function(a){try{return x.gp.CE(a.nodeName),i}catch(b){}return n};function ia(a,b){a&&this.mo(a,b)}x.f(ia,ha);w=ia.prototype;w.target=l;w.relatedTarget=l;w.offsetX=0;w.offsetY=0;w.clientX=0;w.clientY=0;w.screenX=0;w.screenY=0;w.button=0;w.keyCode=0;w.charCode=0;w.ctrlKey=n;w.altKey=n;w.shiftKey=n;w.metaKey=n;w.lq=l;
w.mo=function(a,b){var c=this.type=a.type;ha.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?x.userAgent.Dv&&(x.gp.VJ(e)||(e=l)):c==y.zh?e=a.fromElement:c==y.yh&&(e=a.toElement);this.relatedTarget=e;this.offsetX=x.userAgent.Pl||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=x.userAgent.Pl||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.lq=a;delete this.Ju;delete this.ep};w.stopPropagation=function(){ia.b.stopPropagation.call(this);this.lq.stopPropagation?this.lq.stopPropagation():this.lq.cancelBubble=i};
w.preventDefault=function(){ia.b.preventDefault.call(this);var a=this.lq;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,fa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};w.em=function(){ia.b.em.call(this);this.relatedTarget=this.currentTarget=this.target=this.lq=l};x.r.wF=o();x.r.wF.prototype.Na=o();x.r.wF.prototype.Pb=o();function ja(){}var ka=0;w=ja.prototype;w.key=0;w.hp=n;w.IA=n;w.mo=function(a,b,c,e,f,g){x.Jx(a)?this.BH=i:a&&a.handleEvent&&x.Jx(a.handleEvent)?this.BH=n:d(Error("Invalid listener argument"));this.er=a;this.FI=b;this.src=c;this.type=e;this.capture=!!f;this.tx=g;this.IA=n;this.key=++ka;this.hp=n};w.handleEvent=function(a){return this.BH?this.er.call(this.tx||this.src,a):this.er.handleEvent.call(this.er,a)};x.object={};x.object.forEach=function(a,b,c){for(var e in a)b.call(c,a[e],e,a)};x.object.filter=function(a,b,c){var e={},f;for(f in a)b.call(c,a[f],f,a)&&(e[f]=a[f]);return e};x.object.map=function(a,b,c){var e={},f;for(f in a)e[f]=b.call(c,a[f],f,a);return e};x.object.some=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return i;return n};x.object.every=function(a,b,c){for(var e in a)if(!b.call(c,a[e],e,a))return n;return i};x.object.vm=function(a){var b=0,c;for(c in a)b++;return b};
x.object.tO=function(a){for(var b in a)return b};x.object.uO=function(a){for(var b in a)return a[b]};x.object.contains=function(a,b){return x.object.cq(a,b)};x.object.of=function(a){var b=[],c=0,e;for(e in a)b[c++]=a[e];return b};x.object.Qf=function(a){var b=[],c=0,e;for(e in a)b[c++]=e;return b};x.object.KO=function(a,b){for(var c=x.Fe(b),e=c?b:arguments,c=c?0:1;c<e.length&&!(a=a[e[c]],!x.to(a));c++);return a};x.object.Gj=function(a,b){return b in a};
x.object.cq=function(a,b){for(var c in a)if(a[c]==b)return i;return n};x.object.zK=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return e};x.object.rO=function(a,b,c){return(b=x.object.zK(a,b,c))&&a[b]};x.object.Xh=function(a){for(var b in a)return n;return i};x.object.clear=function(a){for(var b in a)delete a[b]};x.object.remove=function(a,b){var c;(c=b in a)&&delete a[b];return c};
x.object.add=function(a,b,c){b in a&&d(Error('The object already contains the key "'+b+'"'));x.object.set(a,b,c)};x.object.get=function(a,b,c){return b in a?a[b]:c};x.object.set=function(a,b,c){a[b]=c};x.object.CP=function(a,b,c){return b in a?a[b]:a[b]=c};x.object.ia=function(a){var b={},c;for(c in a)b[c]=a[c];return b};x.object.mM=function(a){var b=x.tj(a);if("object"==b||"array"==b){if(a.ia)return a.ia();var b="array"==b?[]:{},c;for(c in a)b[c]=x.object.mM(a[c]);return b}return a};
x.object.gM=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};x.object.xF="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");x.object.extend=function(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var g=0;g<x.object.xF.length;g++)c=x.object.xF[g],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};
x.object.create=function(a){var b=arguments.length;if(1==b&&x.isArray(arguments[0]))return x.object.create.apply(l,arguments[0]);b%2&&d(Error("Uneven number of arguments"));for(var c={},e=0;e<b;e+=2)c[arguments[e]]=arguments[e+1];return c};x.object.eK=function(a){var b=arguments.length;if(1==b&&x.isArray(arguments[0]))return x.object.eK.apply(l,arguments[0]);for(var c={},e=0;e<b;e++)c[arguments[e]]=i;return c};x.r.vM=n;x.r.Md={};x.r.Cg={};x.r.vk={};x.r.FL="on";x.r.ED={};x.r.dP="_";
x.r.Na=function(a,b,c,e,f){if(b){if(x.isArray(b)){for(var g=0;g<b.length;g++)x.r.Na(a,b[g],c,e,f);return l}var e=!!e,j=x.r.Cg;b in j||(j[b]={pc:0,hi:0});j=j[b];e in j||(j[e]={pc:0,hi:0},j.pc++);var j=j[e],k=x.Am(a),m;j.hi++;if(j[k]){m=j[k];for(g=0;g<m.length;g++)if(j=m[g],j.er==c&&j.tx==f){if(j.hp)break;return m[g].key}}else m=j[k]=[],j.pc++;g=x.r.TK();g.src=a;j=new ja;j.mo(c,g,a,b,e,f);c=j.key;g.key=c;m.push(j);x.r.Md[c]=j;x.r.vk[k]||(x.r.vk[k]=[]);x.r.vk[k].push(j);a.addEventListener?(a==x.global||
!a.gG)&&a.addEventListener(b,g,e):a.attachEvent(x.r.ZG(b),g);return c}d(Error("Invalid event type"))};x.r.TK=function(){var a=x.r.Dt,b=ea?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b};x.r.rL=function(a,b,c,e,f){if(x.isArray(b))for(var g=0;g<b.length;g++)x.r.rL(a,b[g],c,e,f);else a=x.r.Na(a,b,c,e,f),x.r.Md[a].IA=i};x.r.eP=function(a,b,c,e,f){b.Na(a,c,e,f)};
x.r.Pb=function(a,b,c,e,f){if(x.isArray(b)){for(var g=0;g<b.length;g++)x.r.Pb(a,b[g],c,e,f);return l}e=!!e;a=x.r.cC(a,b,e);if(!a)return n;for(g=0;g<a.length;g++)if(a[g].er==c&&a[g].capture==e&&a[g].tx==f)return x.r.Dz(a[g].key);return n};
x.r.Dz=function(a){if(!x.r.Md[a])return n;var b=x.r.Md[a];if(b.hp)return n;var c=b.src,e=b.type,f=b.FI,g=b.capture;c.removeEventListener?(c==x.global||!c.gG)&&c.removeEventListener(e,f,g):c.detachEvent&&c.detachEvent(x.r.ZG(e),f);c=x.Am(c);f=x.r.Cg[e][g][c];if(x.r.vk[c]){var j=x.r.vk[c];x.Q.remove(j,b);0==j.length&&delete x.r.vk[c]}b.hp=i;f.mI=i;x.r.RF(e,g,c,f);delete x.r.Md[a];return i};x.r.QP=function(a,b,c,e,f){b.Pb(a,c,e,f)};
x.r.RF=function(a,b,c,e){if(!e.Yx&&e.mI){for(var f=0,g=0;f<e.length;f++)e[f].hp?e[f].FI.src=l:(f!=g&&(e[g]=e[f]),g++);e.length=g;e.mI=n;0==g&&(delete x.r.Cg[a][b][c],x.r.Cg[a][b].pc--,0==x.r.Cg[a][b].pc&&(delete x.r.Cg[a][b],x.r.Cg[a].pc--),0==x.r.Cg[a].pc&&delete x.r.Cg[a])}};
x.r.LI=function(a,b,c){var e=0,f=b==l,g=c==l,c=!!c;if(a==l)x.object.forEach(x.r.vk,function(a){for(var j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(g||c==k.capture))x.r.Dz(k.key),e++}});else if(a=x.Am(a),x.r.vk[a])for(var a=x.r.vk[a],j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(g||c==k.capture))x.r.Dz(k.key),e++}return e};x.r.BO=function(a,b,c){return x.r.cC(a,b,c)||[]};x.r.cC=function(a,b,c){var e=x.r.Cg;return b in e&&(e=e[b],c in e&&(e=e[c],a=x.Am(a),e[a]))?e[a]:l};
x.r.AO=function(a,b,c,e,f){e=!!e;if(a=x.r.cC(a,b,e))for(b=0;b<a.length;b++)if(!a[b].hp&&a[b].er==c&&a[b].capture==e&&a[b].tx==f)return a[b];return l};x.r.NO=function(a,b,c){var a=x.Am(a),e=x.r.vk[a];if(e){var f=x.to(b),g=x.to(c);return f&&g?(e=x.r.Cg[b],!!e&&!!e[c]&&a in e[c]):!f&&!g?i:x.Q.some(e,function(a){return f&&a.type==b||g&&a.capture==c})}return n};x.r.oO=function(a){var b=[],c;for(c in a)a[c]&&a[c].id?b.push(c+" = "+a[c]+" ("+a[c].id+")"):b.push(c+" = "+a[c]);return b.join("\n")};
x.r.ZG=function(a){return a in x.r.ED?x.r.ED[a]:x.r.ED[a]=x.r.FL+a};x.r.sO=function(a,b,c,e){var f=x.r.Cg;return b in f&&(f=f[b],c in f)?x.r.pq(f[c],a,b,c,e):i};x.r.pq=function(a,b,c,e,f){var g=1,b=x.Am(b);if(a[b]){a.hi--;a=a[b];a.Yx?a.Yx++:a.Yx=1;try{for(var j=a.length,k=0;k<j;k++){var m=a[k];m&&!m.hp&&(g&=x.r.MB(m,f)!==n)}}finally{a.Yx--,x.r.RF(c,e,b,a)}}return Boolean(g)};x.r.MB=function(a,b){var c=a.handleEvent(b);a.IA&&x.r.Dz(a.key);return c};x.r.IO=function(){return x.object.vm(x.r.Md)};
x.r.dispatchEvent=function(a,b){var c=b.type||b,e=x.r.Cg;if(!(c in e))return i;if(x.Gc(b))b=new ha(b,a);else if(b instanceof ha)b.target=b.target||a;else{var f=b,b=new ha(c,a);x.object.extend(b,f)}var f=1,g,e=e[c],c=i in e,j;if(c){g=[];for(j=a;j;j=j.LD)g.push(j);j=e[i];j.hi=j.pc;for(var k=g.length-1;!b.ep&&0<=k&&j.hi;k--)b.currentTarget=g[k],f&=x.r.pq(j,g[k],b.type,i,b)&&b.Ju!=n}if(n in e)if(j=e[n],j.hi=j.pc,c)for(k=0;!b.ep&&k<g.length&&j.hi;k++)b.currentTarget=g[k],f&=x.r.pq(j,g[k],b.type,n,b)&&
b.Ju!=n;else for(e=a;!b.ep&&e&&j.hi;e=e.LD)b.currentTarget=e,f&=x.r.pq(j,e,b.type,n,b)&&b.Ju!=n;return Boolean(f)};x.r.rP=function(a){x.r.Dt=a.EI(x.r.Dt)};
x.r.Dt=function(a,b){if(!x.r.Md[a])return i;var c=x.r.Md[a],e=c.type,f=x.r.Cg;if(!(e in f))return i;var f=f[e],g,j;if(!ea){g=b||x.QK();var k=i in f,m=n in f;if(k){if(x.r.mL(g))return i;x.r.wL(g)}var q=new ia;q.mo(g,this);g=i;try{if(k){for(var s=[],u=q.currentTarget;u;u=u.parentNode)s.push(u);j=f[i];j.hi=j.pc;for(var v=s.length-1;!q.ep&&0<=v&&j.hi;v--)q.currentTarget=s[v],g&=x.r.pq(j,s[v],e,i,q);if(m){j=f[n];j.hi=j.pc;for(v=0;!q.ep&&v<s.length&&j.hi;v++)q.currentTarget=s[v],g&=x.r.pq(j,s[v],e,n,q)}}else g=
x.r.MB(c,q)}finally{s&&(s.length=0),q.Ii()}return g}e=new ia(b,this);try{g=x.r.MB(c,e)}finally{e.Ii()}return g};x.r.wL=function(a){var b=n;if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=i}if(b||a.returnValue==h)a.returnValue=i};x.r.mL=function(a){return 0>a.keyCode||a.returnValue!=h};x.r.kM=0;x.r.JO=function(a){return a+"_"+x.r.kM++};x.debug.Ce.JI(function(a){x.r.Dt=a(x.r.Dt)});function ma(){}x.f(ma,ga);w=ma.prototype;w.gG=i;w.LD=l;w.addEventListener=function(a,b,c,e){x.r.Na(this,a,b,c,e)};w.removeEventListener=function(a,b,c,e){x.r.Pb(this,a,b,c,e)};w.dispatchEvent=function(a){return x.r.dispatchEvent(this,a)};w.em=function(){ma.b.em.call(this);x.r.LI(this);this.LD=l};var na=x.global.window;x.Ut={};x.Ut.oL=function(a){return/^\s*$/.test(a)?n:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};x.Ut.parse=function(a){a=""+a;if(x.Ut.oL(a))try{return eval("("+a+")")}catch(b){}d(Error("Invalid JSON string: "+a))};x.Ut.SP=function(a){return eval("("+a+")")};x.Ut.ab=function(a,b){return(new oa(b)).ab(a)};
function oa(a){this.Cy=a}oa.prototype.ab=function(a){var b=[];pa(this,a,b);return b.join("")};
function pa(a,b,c){switch(typeof b){case "string":qa(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(x.isArray(b)){var e=b.length;c.push("[");for(var f="",g=0;g<e;g++)c.push(f),f=b[g],pa(a,a.Cy?a.Cy.call(b,""+g,f):f,c),f=",";c.push("]");break}c.push("{");e="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(f=b[g],"function"!=typeof f&&(c.push(e),qa(g,c),
c.push(":"),pa(a,a.Cy?a.Cy.call(b,g,f):f,c),e=","));c.push("}");break;case "function":break;default:d(Error("Unknown type: "+typeof b))}}var ra={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},sa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function qa(a,b){b.push('"',a.replace(sa,function(a){if(a in ra)return ra[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return ra[a]=f+b.toString(16)}),'"')};x.Wi={};function ta(){}ta.prototype.JF=l;ta.prototype.xt=function(){var a;if(!(a=this.JF))a={},ua(this)&&(a[0]=i,a[1]=i),a=this.JF=a;return a};function va(a,b){this.sM=a;this.IL=b}x.f(va,ta);va.prototype.VA=function(){return this.sM()};va.prototype.xt=function(){return this.IL()};x.Wi.wj=function(){return x.Wi.wj.JG.VA()};x.Wi.wj.xt=function(){return x.Wi.wj.JG.xt()};x.Wi.wj.AP=function(a,b){x.Wi.wj.VI(new va(a,b))};x.Wi.wj.VI=function(a){x.Wi.wj.JG=a};function wa(){}x.f(wa,ta);wa.prototype.VA=function(){var a=ua(this);return a?new ActiveXObject(a):new XMLHttpRequest};wa.prototype.BC=l;
function ua(a){if(!a.BC&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var e=b[c];try{return new ActiveXObject(e),a.BC=e}catch(f){}}d(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.BC}x.Wi.wj.VI(new wa);x.od={};x.od.vm=function(a){return"function"==typeof a.vm?a.vm():x.Fe(a)||x.Gc(a)?a.length:x.object.vm(a)};x.od.of=function(a){if("function"==typeof a.of)return a.of();if(x.Gc(a))return a.split("");if(x.Fe(a)){for(var b=[],c=a.length,e=0;e<c;e++)b.push(a[e]);return b}return x.object.of(a)};x.od.Qf=function(a){if("function"==typeof a.Qf)return a.Qf();if("function"!=typeof a.of){if(x.Fe(a)||x.Gc(a)){for(var b=[],a=a.length,c=0;c<a;c++)b.push(c);return b}return x.object.Qf(a)}};
x.od.contains=function(a,b){return"function"==typeof a.contains?a.contains(b):"function"==typeof a.cq?a.cq(b):x.Fe(a)||x.Gc(a)?x.Q.contains(a,b):x.object.cq(a,b)};x.od.Xh=function(a){return"function"==typeof a.Xh?a.Xh():x.Fe(a)||x.Gc(a)?x.Q.Xh(a):x.object.Xh(a)};x.od.clear=function(a){"function"==typeof a.clear?a.clear():x.Fe(a)?x.Q.clear(a):x.object.clear(a)};
x.od.forEach=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(x.Fe(a)||x.Gc(a))x.Q.forEach(a,b,c);else for(var e=x.od.Qf(a),f=x.od.of(a),g=f.length,j=0;j<g;j++)b.call(c,f[j],e&&e[j],a)};x.od.filter=function(a,b,c){if("function"==typeof a.filter)return a.filter(b,c);if(x.Fe(a)||x.Gc(a))return x.Q.filter(a,b,c);var e,f=x.od.Qf(a),g=x.od.of(a),j=g.length;if(f){e={};for(var k=0;k<j;k++)b.call(c,g[k],f[k],a)&&(e[f[k]]=g[k])}else{e=[];for(k=0;k<j;k++)b.call(c,g[k],h,a)&&e.push(g[k])}return e};
x.od.map=function(a,b,c){if("function"==typeof a.map)return a.map(b,c);if(x.Fe(a)||x.Gc(a))return x.Q.map(a,b,c);var e,f=x.od.Qf(a),g=x.od.of(a),j=g.length;if(f){e={};for(var k=0;k<j;k++)e[f[k]]=b.call(c,g[k],f[k],a)}else{e=[];for(k=0;k<j;k++)e[k]=b.call(c,g[k],h,a)}return e};x.od.some=function(a,b,c){if("function"==typeof a.some)return a.some(b,c);if(x.Fe(a)||x.Gc(a))return x.Q.some(a,b,c);for(var e=x.od.Qf(a),f=x.od.of(a),g=f.length,j=0;j<g;j++)if(b.call(c,f[j],e&&e[j],a))return i;return n};
x.od.every=function(a,b,c){if("function"==typeof a.every)return a.every(b,c);if(x.Fe(a)||x.Gc(a))return x.Q.every(a,b,c);for(var e=x.od.Qf(a),f=x.od.of(a),g=f.length,j=0;j<g;j++)if(!b.call(c,f[j],e&&e[j],a))return n;return i};x.gb={};x.gb.uf="StopIteration"in x.global?x.global.StopIteration:Error("StopIteration");function xa(){}xa.prototype.next=function(){d(x.gb.uf)};xa.prototype.cA=function(){return this};x.gb.vh=function(a){if(a instanceof xa)return a;if("function"==typeof a.cA)return a.cA(n);if(x.Fe(a)){var b=0,c=new xa;c.next=function(){for(;;){b>=a.length&&d(x.gb.uf);if(b in a)return a[b++];b++}};return c}d(Error("Not implemented"))};
x.gb.forEach=function(a,b,c){if(x.Fe(a))try{x.Q.forEach(a,b,c)}catch(e){e!==x.gb.uf&&d(e)}else{a=x.gb.vh(a);try{for(;;)b.call(c,a.next(),h,a)}catch(f){f!==x.gb.uf&&d(f)}}};x.gb.filter=function(a,b,c){var a=x.gb.vh(a),e=new xa;e.next=function(){for(;;){var e=a.next();if(b.call(c,e,h,a))return e}};return e};
x.gb.uP=function(a,b,c){var e=0,f=a,g=c||1;1<arguments.length&&(e=a,f=b);0==g&&d(Error("Range step argument must not be zero"));var j=new xa;j.next=function(){(g>0&&e>=f||g<0&&e<=f)&&d(x.gb.uf);var a=e;e=e+g;return a};return j};x.gb.join=function(a,b){return x.gb.XE(a).join(b)};x.gb.map=function(a,b,c){var a=x.gb.vh(a),e=new xa;e.next=function(){for(;;){var e=a.next();return b.call(c,e,h,a)}};return e};x.gb.reduce=function(a,b,c,e){var f=c;x.gb.forEach(a,function(a){f=b.call(e,f,a)});return f};
x.gb.some=function(a,b,c){a=x.gb.vh(a);try{for(;;)if(b.call(c,a.next(),h,a))return i}catch(e){e!==x.gb.uf&&d(e)}return n};x.gb.every=function(a,b,c){a=x.gb.vh(a);try{for(;;)if(!b.call(c,a.next(),h,a))return n}catch(e){e!==x.gb.uf&&d(e)}return i};x.gb.aO=function(a){var b=arguments,c=b.length,e=0,f=new xa;f.next=function(){try{return e>=c&&d(x.gb.uf),x.gb.vh(b[e]).next()}catch(a){return(a!==x.gb.uf||e>=c)&&d(a),e++,this.next()}};return f};
x.gb.lO=function(a,b,c){var a=x.gb.vh(a),e=new xa,f=i;e.next=function(){for(;;){var e=a.next();if(!f||!b.call(c,e,h,a))return f=n,e}};return e};x.gb.KP=function(a,b,c){var a=x.gb.vh(a),e=new xa,f=i;e.next=function(){for(;;)if(f){var e=a.next();if(b.call(c,e,h,a))return e;f=n}else d(x.gb.uf)};return e};x.gb.XE=function(a){if(x.Fe(a))return x.Q.XE(a);var a=x.gb.vh(a),b=[];x.gb.forEach(a,function(a){b.push(a)});return b};
x.gb.FB=function(a,b){var a=x.gb.vh(a),b=x.gb.vh(b),c,e;try{for(;;){c=e=n;var f=a.next();c=i;var g=b.next();e=i;if(f!=g)break}}catch(j){j!==x.gb.uf&&d(j);if(c&&!e)return n;if(!e)try{b.next()}catch(k){return k!==x.gb.uf&&d(k),i}}return n};x.gb.jP=function(a,b){try{return x.gb.vh(a).next()}catch(c){return c!=x.gb.uf&&d(c),b}};
x.gb.product=function(a){if(x.Q.some(arguments,function(a){return!a.length})||!arguments.length)return new xa;var b=new xa,c=arguments,e=x.Q.repeat(0,c.length);b.next=function(){if(e){for(var a=x.Q.map(e,function(a,b){return c[b][a]}),b=e.length-1;0<=b;b--){if(e[b]<c[b].length-1){e[b]++;break}if(0==b){e=l;break}e[b]=0}return a}d(x.gb.uf)};return b};
x.gb.jO=function(a){var b=x.gb.vh(a),c=[],e=0,a=new xa,f=n;a.next=function(){var a=l;if(!f)try{return a=b.next(),c.push(a),a}catch(j){(j!=x.gb.uf||x.Q.Xh(c))&&d(j),f=i}a=c[e];e=(e+1)%c.length;return a};return a};function ya(a,b){this.Eg={};this.Ma=[];var c=arguments.length;if(1<c){c%2&&d(Error("Uneven number of arguments"));for(var e=0;e<c;e+=2)this.set(arguments[e],arguments[e+1])}else if(a){a instanceof ya?(c=a.Qf(),e=a.of()):(c=x.object.Qf(a),e=x.object.of(a));for(var f=0;f<c.length;f++)this.set(c[f],e[f])}}w=ya.prototype;w.pc=0;w.wv=0;w.vm=r("pc");w.of=function(){za(this);for(var a=[],b=0;b<this.Ma.length;b++)a.push(this.Eg[this.Ma[b]]);return a};w.Qf=function(){za(this);return this.Ma.concat()};
w.Gj=function(a){return Aa(this.Eg,a)};w.cq=function(a){for(var b=0;b<this.Ma.length;b++){var c=this.Ma[b];if(Aa(this.Eg,c)&&this.Eg[c]==a)return i}return n};w.FB=function(a,b){if(this===a)return i;if(this.pc!=a.vm())return n;var c=b||Ba;za(this);for(var e,f=0;e=this.Ma[f];f++)if(!c(this.get(e),a.get(e)))return n;return i};function Ba(a,b){return a===b}w.Xh=function(){return 0==this.pc};w.clear=function(){this.Eg={};this.wv=this.pc=this.Ma.length=0};
w.remove=function(a){return Aa(this.Eg,a)?(delete this.Eg[a],this.pc--,this.wv++,this.Ma.length>2*this.pc&&za(this),i):n};function za(a){if(a.pc!=a.Ma.length){for(var b=0,c=0;b<a.Ma.length;){var e=a.Ma[b];Aa(a.Eg,e)&&(a.Ma[c++]=e);b++}a.Ma.length=c}if(a.pc!=a.Ma.length){for(var f={},c=b=0;b<a.Ma.length;)e=a.Ma[b],Aa(f,e)||(a.Ma[c++]=e,f[e]=1),b++;a.Ma.length=c}}w.get=function(a,b){return Aa(this.Eg,a)?this.Eg[a]:b};
w.set=function(a,b){Aa(this.Eg,a)||(this.pc++,this.Ma.push(a),this.wv++);this.Eg[a]=b};w.ia=function(){return new ya(this)};w.gM=function(){for(var a=new ya,b=0;b<this.Ma.length;b++){var c=this.Ma[b];a.set(this.Eg[c],c)}return a};w.cA=function(a){za(this);var b=0,c=this.Ma,e=this.Eg,f=this.wv,g=this,j=new xa;j.next=function(){for(;;){f!=g.wv&&d(Error("The map has changed since the iterator was created"));b>=c.length&&d(x.gb.uf);var j=c[b++];return a?j:e[j]}};return j};
function Aa(a,b){return Object.prototype.hasOwnProperty.call(a,b)};x.uri={};x.uri.J={};x.uri.J.HF=function(a,b,c,e,f,g,j){var k=[];a&&k.push(a,":");c&&(k.push("//"),b&&k.push(b,"@"),k.push(c),e&&k.push(":",e));f&&k.push(f);g&&k.push("?",g);j&&k.push("#",j);return k.join("")};x.uri.J.bM=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");x.uri.J.split=function(a){return a.match(x.uri.J.bM)};x.uri.J.zw=function(a){return a&&decodeURIComponent(a)};
x.uri.J.xq=function(a,b){return x.uri.J.split(b)[a]||l};x.uri.J.lC=function(a){return x.uri.J.xq(1,a)};x.uri.J.KK=function(a){a=x.uri.J.lC(a);!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1));return a?a.toLowerCase():""};x.uri.J.$K=function(a){return x.uri.J.xq(2,a)};x.uri.J.fH=function(a){return x.uri.J.zw(x.uri.J.$K(a))};x.uri.J.JK=function(a){return x.uri.J.xq(3,a)};x.uri.J.TG=function(a){return x.uri.J.zw(x.uri.J.JK(a))};
x.uri.J.hC=function(a){return Number(x.uri.J.xq(4,a))||l};x.uri.J.SK=function(a){return x.uri.J.xq(5,a)};x.uri.J.yt=function(a){return x.uri.J.zw(x.uri.J.SK(a))};x.uri.J.aH=function(a){return x.uri.J.xq(6,a)};x.uri.J.MK=function(a){var b=a.indexOf("#");return 0>b?l:a.substr(b+1)};x.uri.J.BP=function(a,b){return x.uri.J.QL(a)+(b?"#"+b:"")};x.uri.J.UG=function(a){return x.uri.J.zw(x.uri.J.MK(a))};x.uri.J.xO=function(a){a=x.uri.J.split(a);return x.uri.J.HF(a[1],a[2],a[3],a[4])};
x.uri.J.HO=function(a){a=x.uri.J.split(a);return x.uri.J.HF(l,l,l,l,a[5],a[6],a[7])};x.uri.J.QL=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};x.uri.J.QO=function(a,b){var c=x.uri.J.split(a),e=x.uri.J.split(b);return c[3]==e[3]&&c[1]==e[1]&&c[4]==e[4]};x.uri.J.RJ=function(a){x.$z&&(0<=a.indexOf("#")||0<=a.indexOf("?"))&&d(Error("goog.uri.utils: Fragment or query identifiers are not supported: ["+a+"]"))};
x.uri.J.fA=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=h)}return a.join("")};x.uri.J.AF=function(a,b,c){if(x.isArray(b))for(var e=0;e<b.length;e++)c.push("&",a),""!==b[e]&&c.push("=",x.N.Wr(b[e]));else b!=l&&(c.push("&",a),""!==b&&c.push("=",x.N.Wr(b)))};x.uri.J.yA=function(a,b,c){for(c=c||0;c<b.length;c+=2)x.uri.J.AF(b[c],b[c+1],a);return a};
x.uri.J.WN=function(a,b){var c=x.uri.J.yA([],a,b);c[0]="";return c.join("")};x.uri.J.IF=function(a,b){for(var c in b)x.uri.J.AF(c,b[c],a);return a};x.uri.J.XN=function(a){a=x.uri.J.IF([],a);a[0]="";return a.join("")};x.uri.J.GN=function(a,b){return x.uri.J.fA(2==arguments.length?x.uri.J.yA([a],arguments[1],0):x.uri.J.yA([a],arguments,1))};x.uri.J.HN=function(a,b){return x.uri.J.fA(x.uri.J.IF([a],b))};x.uri.J.QJ=function(a,b){return x.uri.J.fA([a,"&","zx","=",x.N.Wr(b)])};
x.uri.J.Uw=function(a,b,c,e){for(var f=c.length;0<=(b=a.indexOf(c,b))&&b<e;){var g=a.charCodeAt(b-1);if(38==g||63==g)if(g=a.charCodeAt(b+f),!g||61==g||38==g||35==g)return b;b+=f+1}return-1};x.uri.J.ux=/#|$/;x.uri.J.OO=function(a,b){return 0<=x.uri.J.Uw(a,0,b,a.search(x.uri.J.ux))};x.uri.J.FO=function(a,b){var c=a.search(x.uri.J.ux),e=x.uri.J.Uw(a,0,b,c);if(0>e)return l;var f=a.indexOf("&",e);if(0>f||f>c)f=c;e+=b.length+1;return x.N.Gz(a.substr(e,f-e))};
x.uri.J.GO=function(a,b){for(var c=a.search(x.uri.J.ux),e=0,f,g=[];0<=(f=x.uri.J.Uw(a,e,b,c));){e=a.indexOf("&",f);if(0>e||e>c)e=c;f+=b.length+1;g.push(x.N.Gz(a.substr(f,e-f)))}return g};x.uri.J.fM=/[?&]($|#)/;x.uri.J.RL=function(a){for(var b=a.search(x.uri.J.ux),c=0,e,f=[];0<=(e=x.uri.J.Uw(a,c,"zx",b));)f.push(a.substring(c,e)),c=Math.min(a.indexOf("&",e)+1||b,b);f.push(a.substr(c));return f.join("").replace(x.uri.J.fM,"$1")};
x.uri.J.$L=function(a){var b=x.N.bH();return x.uri.J.QJ(x.uri.J.RL(a),b)};x.uri.J.IN=function(a,b){x.uri.J.RJ(a);x.N.xK(a)&&(a=a.substr(0,a.length-1));x.N.cM(b)&&(b=b.substr(1));return x.N.UJ(a,"/",b)};x.uri.J.vL=function(a){return x.uri.J.$L(a)};function Ca(a){ma.call(this);this.headers=new ya;this.Vz=a||l}x.f(Ca,ma);Ca.vF="Content-Type";Ca.KJ=/^https?$/i;Ca.HJ="application/x-www-form-urlencoded;charset=utf-8";Ca.eE=[];Ca.send=function(a,b,c,e,f,g){var j=new Ca;Ca.eE.push(j);b&&x.r.Na(j,"complete",b);x.r.Na(j,"ready",x.xI(Ca.XJ,j));g&&(j.WE=Math.max(0,g));j.send(a,c,e,f)};Ca.bO=function(){for(var a=Ca.eE;a.length;)a.pop().Ii()};Ca.sP=function(a){Ca.prototype.qu=a.EI(Ca.prototype.qu)};Ca.XJ=function(a){a.Ii();x.Q.remove(Ca.eE,a)};w=Ca.prototype;
w.Ql=n;w.tc=l;w.Uz=l;w.WH="";w.GB=n;w.xx=n;w.CC=n;w.lo=n;w.WE=0;w.Bp=l;w.OI="";w.jF=n;
w.send=function(a,b,c,e){this.tc&&d(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.WH=a;this.GB=n;this.Ql=i;this.tc=this.Vz?this.Vz.VA():x.Wi.wj();this.Uz=this.Vz?this.Vz.xt():x.Wi.wj.xt();this.tc.onreadystatechange=x.bind(this.wI,this);try{this.CC=i,this.tc.open(b,a,i),this.CC=n}catch(f){Da(this);return}var a=c||"",g=this.headers.ia();e&&x.od.forEach(e,function(a,b){g.set(b,a)});"POST"==b&&!g.Gj(Ca.vF)&&g.set(Ca.vF,Ca.HJ);x.od.forEach(g,function(a,
b){this.tc.setRequestHeader(b,a)},this);this.OI&&(this.tc.responseType=this.OI);x.object.Gj(this.tc,"withCredentials")&&(this.tc.withCredentials=this.jF);try{this.Bp&&(na.clearTimeout(this.Bp),this.Bp=l),0<this.WE&&(this.Bp=na.setTimeout(x.bind(this.eM,this),this.WE)),this.xx=i,this.tc.send(a),this.xx=n}catch(j){Da(this)}};w.eM=function(){"undefined"!=typeof x&&this.tc&&(this.dispatchEvent("timeout"),this.abort(8))};function Da(a){a.Ql=n;a.tc&&(a.lo=i,a.tc.abort(),a.lo=n);Ea(a);Fa(a)}
function Ea(a){a.GB||(a.GB=i,a.dispatchEvent("complete"),a.dispatchEvent("error"))}w.abort=function(){this.tc&&this.Ql&&(this.Ql=n,this.lo=i,this.tc.abort(),this.lo=n,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Fa(this))};w.em=function(){this.tc&&(this.Ql&&(this.Ql=n,this.lo=i,this.tc.abort(),this.lo=n),Fa(this,i));Ca.b.em.call(this)};w.wI=function(){!this.CC&&!this.xx&&!this.lo?this.qu():Ga(this)};w.qu=function(){Ga(this)};
function Ga(a){if(a.Ql&&"undefined"!=typeof x&&(!a.Uz[1]||!(4==(a.tc?a.tc.readyState:0)&&2==Ha(a))))if(a.xx&&4==(a.tc?a.tc.readyState:0))na.setTimeout(x.bind(a.wI,a),0);else if(a.dispatchEvent("readystatechange"),4==(a.tc?a.tc.readyState:0)){a.Ql=n;var b=Ha(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 304:case 1223:c=i;break a;default:c=n}if(!c){if(b=0===b)b=x.uri.J.KK(""+a.WH),b=!Ca.KJ.test(b);c=b}c?(a.dispatchEvent("complete"),a.dispatchEvent("success")):Ea(a);Fa(a)}}
function Fa(a,b){if(a.tc){var c=a.tc,e=a.Uz[0]?x.oI:l;a.tc=l;a.Uz=l;a.Bp&&(na.clearTimeout(a.Bp),a.Bp=l);b||a.dispatchEvent("ready");try{c.onreadystatechange=e}catch(f){}}}function Ha(a){try{return 2<(a.tc?a.tc.readyState:0)?a.tc.status:-1}catch(b){return-1}}x.debug.Ce.JI(function(a){Ca.prototype.qu=a(Ca.prototype.qu)});function Ia(a){a=typeof a;return"string"==a||"number"==a||"boolean"==a}function Ja(a){return"string"!=typeof a&&"undefined"!=typeof a.length}
function Ka(a,b){var c="<"+a;"undefined"!=typeof b.functionName&&(b["function"]=b.functionName,delete b.functionName);for(var e in b)"format"!=e&&"text"!=e&&"custom_attribute_value"!=e&&"attr"!=e&&Ia(b[e])&&(c+=" "+e+'="'+b[e]+'"');c+=">";for(e in b)if("arg"==e&&Ja(b[e]))for(var f=b[e],g=0;g<f.length;g++)c+="<arg><![CDATA["+f[g]+"]]\></arg>";else if("custom_attribute_value"==e||"attr"==e)c+="<![CDATA["+b[e]+"]]\>";else if("format"==e||"text"==e)c+="<"+e+"><![CDATA["+b[e]+"]]\></"+e+">";else if(Ja(b[e])){f=
b[e];for(g=0;g<f.length;g++)c+=Ka(e,f[g])}else Ia(b[e])||(c+=Ka(e,b[e]));return c+("</"+a+">")}function La(){}w=La.prototype;w.ea=l;w.n=l;w.rm=l;w.my=l;w.ly=l;w.lI=l;w.xD=l;w.Tw=l;w.mo=function(a){this.ea=a;this.xD=this.lI=this.ly=this.my=this.il=n;this.Hh=this.ea.enableFirefoxPrintPreviewFix};w.il=n;w.rI=function(){this.il=i;this.my&&this.oi(this.ea.xmlFile);this.ly&&this.uh(this.ea.xmlData);this.lI&&this.kn(this.ea.jsonFile);this.xD&&this.jj(this.ea.jsonData)};w.sI=function(){this.Hh&&Ma(this)};
w.Lc=t(l);w.Gt=function(){this.ea.visible=n;this.n&&(this.n.style.visibility="hidden",this.n.setAttribute("width","1px"),this.n.setAttribute("height","1px"))};w.show=function(){this.ea.visible=i;this.n&&(this.n.style.visibility="visible",this.n.setAttribute("width",this.Qa+""),this.n.setAttribute("height",this.$a+""))};
w.iq=function(a,b){a&&"OBJECT"==a.nodeName&&(z.platform.Tq&&z.platform.Bo?(a.style.display="none",function(){4==a.readyState?(z.platform.hk&&b!=l&&z.ct(window[b]),z.ct(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))};w.ct=function(a){for(var b in a)"function"==typeof a[b]&&(a[b]=l);a.parentNode&&a.parentNode.removeChild(a)};w.Jn=function(){return z.platform.xC&&this.ea.swfFile!=l};
w.write=function(a){var b=this.ea.width+"",c=this.ea.height+"",e=this.ea.preloaderSWFFile?this.ea.preloaderSWFFile:this.ea.swfFile;if(this.Hh=this.Hh&&z.platform.zH)this.Tw=new Na;if(z.platform.Tq&&z.platform.Bo){var f;f='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+(' id="'+this.ea.id+'"');f=f+(' width="'+b+'"')+(' height="'+c+'"')+(' style="visibility:'+(this.ea.visible?"visible":"hidden")+'"');f+=' codebase="'+z.platform.protocol+'//fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">';
f+=Oa("movie",e);f+=Oa("bgcolor",this.ea.bgColor);f+=Oa("allowScriptAccess","always");f+=Oa("flashvars",Pa(this));this.ea.wMode!=l&&(f+=Oa("wmode",this.ea.wMode));f+="</object>";if(z.platform.hk){b=l;for(c=a;c;){if(c.nodeName!=l&&"form"==c.nodeName.toLowerCase()){b=c;break}c=c.parentNode}if(b!=l){window[this.ea.id]={};window[this.ea.id].LJ=o();a.innerHTML=f;window[this.ea.id].LJ=l;var a={},g;for(g in window[this.ea.id])"function"==typeof window[this.ea.id][g]&&(a[g]=window[this.ea.id][g]);this.n=
window[this.ea.id]=b[this.ea.id];this.ea.flashObject=this.n;for(g in a)Qa(g)}else a.innerHTML=f,this.n=document.getElementById(this.ea.id),this.ea.flashObject=this.n}else a.innerHTML=f,this.n=document.getElementById(this.ea.id),this.ea.flashObject=this.n}else{g=document.createElement("object");g.setAttribute("type","application/x-shockwave-flash");g.setAttribute("id",this.ea.id);g.setAttribute("width",b);g.setAttribute("height",c);g.setAttribute("data",e);g.setAttribute("style","visibility: "+(this.ea.visible?
"visible":"hidden"));Ra(g,"movie",e);Ra(g,"bgcolor",this.ea.bgColor);Ra(g,"allowScriptAccess","always");Ra(g,"flashvars",Pa(this));this.ea.wMode!=l&&Ra(g,"wmode",this.ea.wMode);if(a.hasChildNodes())for(;0<a.childNodes.length;)a.removeChild(a.firstChild);this.n=a.appendChild(g);this.ea.flashObject=this.n;this.rm=a}return this.n!=l};function Oa(a,b){return'<param name="'+a+'" value="'+b+'" />'}
function Ra(a,b,c){var e=document.createElement("param");e.setAttribute("name",b);e.setAttribute("value",c);a.appendChild(e)}function Qa(a){eval('obj[functionName] = function(){return eval(this.CallFunction("<invoke name=\\"'+a+'\\" returntype=\\"javascript\\">" + __flash__argumentsToXML(arguments,0) + "</invoke>"));}')}
function Pa(a){var b="__externalobjid="+a.ea.id;a.ea.preloaderSWFFile&&(b+="&swffile="+a.ea.swfFile);a.ea.xmlFile&&(b+="&xmlfile="+a.ea.xmlFile);a.ea.enabledChartEvents&&(b+="&__enableevents=1");a.ea.enabledChartMouseEvents&&(b+="&__enablechartmouseevents=1");b+="&preloaderInit="+a.ea.messages.preloaderInit;b+="&preloaderLoading="+a.ea.messages.preloaderLoading;b+="&init="+a.ea.messages.init;b+="&loadingConfig="+a.ea.messages.loadingConfig;b+="&loadingTemplates="+a.ea.messages.loadingTemplates;b+=
"&loadingResources="+a.ea.messages.loadingResources;b+="&noData="+a.ea.messages.noData;return b+="&waitingForData="+a.ea.messages.waitingForData}w.As=t(i);w.Fz=function(){(this.Hh||this.rm)&&this.Tw.Ii();Ma(this)};w.sp=function(a,b){this.n&&(this.n.setAttribute("width",a+""),this.n.setAttribute("height",b+""))};
w.remove=function(){this.n&&(this.n.Dispose&&this.n.Dispose(),Sa(this.n,this.Hm),this.Hh&&(this.Hh||this.rm)&&this.Tw.Ii());this.n=l;this.ea.flashObject=this.n;if(z&&z.bL())for(var a=z.YG(),b=0;b<a;b++)if(z.RG()[b]==this){z.RG().splice(b,1);break}z&&z.SG()&&this.Hm!=l&&(z.SG()[this.Hm]=l)};w.clear=function(){this.n&&this.n.Clear&&this.n.Clear()};w.refresh=function(){this.n!=l&&this.n.Refresh!=l&&this.n.Refresh()};w.Sr=function(a,b){this.n!=l&&this.n.UpdateData!=l&&this.n.UpdateData(a,b)};
w.Vy=function(a){this.n&&this.n.SetLoading&&this.n.SetLoading(a)};w.Yw=function(){return this.n.GetInformation()};w.oi=function(a){this.n&&this.il?this.n.SetXMLDataFromURL(a):this.my=i};w.uh=function(a){this.n&&this.il?this.n.SetXMLDataFromString(a):this.ly=i};w.kn=o();w.jj=function(a){this.n&&this.il?this.uh(Ka("anychart",a)):this.xD=i};w.Vu=function(a){this.n&&this.il?this.n.SetXMLDataFromString(a):this.ly=i};w.cz=function(a){this.n&&this.il?this.n.SetXMLDataFromURL(a):this.my=i};
w.tp=function(a,b){this.n&&this.il&&this.n.UpdateViewFromURL(a,b)};w.Zy=function(a,b){this.n&&this.il&&this.n.UpdateViewFromString(a,b)};w.$c=function(a,b){this.n!=l&&this.n.AddPoint!=l&&this.n.AddPoint(a,b)};w.xj=function(a,b,c){this.n!=l&&this.n.AddPointAt!=l&&this.n.AddPointAt(a,b,c)};w.nk=function(a,b){this.n!=l&&this.n.RemovePoint!=l&&this.n.RemovePoint(a,b)};w.Bk=function(a,b,c){this.n!=l&&this.n.UpdatePoint!=l&&this.n.UpdatePoint(a,b,c)};
w.uj=function(a,b,c){this.n!=l&&this.n.UpdatePointData!=l&&this.n.UpdatePointData(a,b,c)};w.Vj=function(a,b,c){this.n!=l&&this.n.HighlightPoint!=l&&this.n.HighlightPoint(a,b,c)};w.fj=function(a,b,c){this.n!=l&&this.n.SelectPoint!=l&&this.n.SelectPoint(a,b,c)};w.Ez=function(a,b,c,e){this.n&&this.n.updatePointWithAnimation!=l&&this.n.updatePointWithAnimation(a,b,c,e)};w.nz=function(){this.n&&this.n.startPointsUpdate!=l&&this.n.startPointsUpdate()};w.yj=function(a){this.n!=l&&this.n.AddSeries!=l&&this.n.AddSeries(a)};
w.zj=function(a,b){this.n!=l&&this.n.AddSeriesAt!=l&&this.n.AddSeriesAt(a,b)};w.ok=function(a){this.n!=l&&this.n.RemoveSeries!=l&&this.n.RemoveSeries(a)};w.Ck=function(a,b){this.n!=l&&this.n.UpdateSeries!=l&&this.n.UpdateSeries(a,b)};w.uk=function(a,b){this.n!=l&&this.n.ShowSeries!=l&&this.n.ShowSeries(a,b)};w.Wj=function(a,b){this.n!=l&&this.n.HighlightSeries!=l&&this.n.HighlightSeries(a,b)};w.Uj=function(a,b){this.n!=l&&this.n.HighlightCategory!=l&&this.n.HighlightCategory(a,b)};
w.jz=function(a,b){this.n!=l&&this.n.ShowAxisMarker!=l&&this.n.ShowAxisMarker(a,b)};w.rk=function(a,b){this.n!=l&&this.n.SetPlotCustomAttribute!=l&&this.n.SetPlotCustomAttribute(a,b)};w.js=function(a,b,c){this.n!=l&&this.n.View_SetPlotCustomAttribute!=l&&this.n.View_SetPlotCustomAttribute(a,b,c)};w.as=function(a,b){this.n!=l&&this.n.View_AddSeries!=l&&this.n.View_AddSeries(a,b)};w.hs=function(a,b){this.n!=l&&this.n.View_RemoveSeries!=l&&this.n.View_RemoveSeries(a,b)};
w.bs=function(a,b,c){this.n!=l&&this.n.View_AddSeriesAt!=l&&this.n.View_AddSeriesAt(a,b,c)};w.ms=function(a,b,c){this.n!=l&&this.n.View_UpdateSeries!=l&&this.n.View_UpdateSeries(a,b,c)};w.ks=function(a,b,c){this.n!=l&&this.n.View_ShowSeries!=l&&this.n.View_ShowSeries(a,b,c)};w.Zr=function(a,b,c){this.n!=l&&this.n.View_AddPoint!=l&&this.n.View_AddPoint(a,b,c)};w.$r=function(a,b,c,e){this.n!=l&&this.n.View_AddPointAt!=l&&this.n.View_AddPointAt(a,b,c,e)};
w.gs=function(a,b,c){this.n!=l&&this.n.View_RemovePoint!=l&&this.n.View_RemovePoint(a,b,c)};w.ls=function(a,b,c,e){this.n!=l&&this.n.View_UpdatePoint!=l&&this.n.View_UpdatePoint(a,b,c,e)};w.Oz=function(a){this.n!=l&&this.n.View_Clear!=l&&this.n.View_Clear(a)};w.fs=function(a){this.n!=l&&this.n.View_Refresh!=l&&this.n.View_Refresh(a)};w.es=function(a,b,c){this.n!=l&&this.n.View_HighlightSeries!=l&&this.n.View_HighlightSeries(a,b,c)};
w.ds=function(a,b,c,e){this.n!=l&&this.n.View_HighlightPoint!=l&&this.n.View_HighlightPoint(a,b,c,e)};w.cs=function(a,b,c){this.n!=l&&this.n.View_HighlightCategory!=l&&this.n.View_HighlightCategory(a,b,c)};w.is=function(a,b,c,e){this.n!=l&&this.n.View_SelectPoint!=l&&this.n.View_SelectPoint(a,b,c,e)};w.Ur=function(a,b,c,e){this.n!=l&&this.n.UpdateViewPointData!=l&&this.n.UpdateViewPointData(a,b,c,e)};w.Bq=function(a,b){return this.n.GetPngScreen(a,b)};
w.kx=function(a,b){return this.n.GetPdfScreen(a,b)};w.zy=function(){this.n.PrintChart()};w.Ly=function(a,b){this.n.SaveAsImage(a,b)};w.My=function(a,b){this.n.SaveAsPDF(a,b)};w.Ny=function(a){this.n!=l&&this.n.ScrollXTo!=l&&this.n.ScrollXTo(a)};w.Oy=function(a){this.n!=l&&this.n.ScrollYTo!=l&&this.n.ScrollYTo(a)};w.scrollTo=function(a,b){this.n!=l&&this.n.ScrollTo!=l&&this.n.ScrollTo(a,b)};w.Lz=function(a,b){this.n!=l&&this.n.ViewScrollXTo!=l&&this.n.ViewScrollXTo(a,b)};
w.Mz=function(a,b){this.n!=l&&this.n.ViewScrollYTo!=l&&this.n.ViewScrollYTo(a,b)};w.px=function(){return this.n!=l&&this.n.GetXScrollInfo!=l?this.n.GetXScrollInfo():l};w.qx=function(){return this.n!=l&&this.n.GetYScrollInfo!=l?this.n.GetYScrollInfo():l};w.nx=function(a){if(this.n!=l&&this.n.GetViewXScrollInfo!=l)return this.n.GetViewXScrollInfo(a)};w.ox=function(a){if(this.n!=l&&this.n.GetViewYScrollInfo!=l)return this.n.GetViewYScrollInfo(a)};w.dz=function(a){this.n!=l&&this.n.SetXZoom!=l&&this.n.SetXZoom(a)};
w.ez=function(a){this.n!=l&&this.n.SetYZoom!=l&&this.n.SetYZoom(a)};w.fz=function(a,b){this.n!=l&&this.n.SetZoom!=l&&this.n.SetZoom(a,b)};w.$y=function(a,b){this.n!=l&&this.n.SetViewXZoom!=l&&this.n.SetViewXZoom(a,b)};w.az=function(a,b){this.n!=l&&this.n.SetViewYZoom!=l&&this.n.SetViewYZoom(a,b)};w.bz=function(a,b,c){this.n!=l&&this.n.SetViewZoom!=l&&this.n.SetViewZoom(a,b,c)};w.Lv=function(){this.n!=l&&this.n.RepeatAnimation!=l&&this.n.RepeatAnimation()};
function Sa(a,b){a&&"OBJECT"==a.nodeName&&(z.platform.Tq&&z.platform.Bo?(a.style.display="none",function(){4==a.readyState?(z.platform.hk&&b&&this.ct(window[b]),z.ct(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))}w.ct=function(a){for(var b in a)"function"==typeof a[b]&&(a[b]=l);a.parentNode&&a.parentNode.removeChild(a)};
function Ma(a){if(a.Hh&&a.rm){var b=a.Bq();if(b&&0!=b.length){var c=a.rm.getAttribute("id");c||(c="__chart_generated_container__"+a.Hm,a.rm.setAttribute("id",c));var e=a.Tw,f=a.rm,g=a.Qa+"",j=a.$a+"",a=a.rm.nodeName,k=document.getElementsByTagName("head");if(k=0<k.length?k[0]:l){var m;m=k;var q=document.createElement("style");q.setAttribute("type","text/css");q.setAttribute("media","screen");var s=a+"#"+c,u=s+" img";q.appendChild(document.createTextNode(s+(" object { width:"+g+"; height:"+j+";padding:0; margin:0; }\n")));
q.appendChild(document.createTextNode(u+" { display: none; }"));m=m.appendChild(q);e.it=m;m=document.createElement("style");m.setAttribute("type","text/css");m.setAttribute("media","print");a=a+"#"+c;c=a+" img";g=" { display: block; width: "+g+"; height: "+j+"; }";m.appendChild(document.createTextNode(a+" object { display: none; }\n"));m.appendChild(document.createTextNode(c+g));g=k.appendChild(m);e.jt=g;g=document.createElement("img");g=f.appendChild(g);g.src="data:image/png;base64,"+b;e.ht=g}}}}
function Na(){}w.it=l;w.jt=l;w.ht=l;Na.prototype.Ii=function(){this.ht&&this.ht.parentNode&&this.ht.parentNode.removeChild(this.ht);this.it&&(this.it.parentNode.removeChild(this.it),this.it=l);this.jt&&(this.jt.parentNode.removeChild(this.jt),this.jt=l)};x.vg("anychart.scope.goog",x);x.vg("anychart.scope.Event",ha);x.vg("anychart.scope.EventTarget",ma);x.vg("anychart.scope.EventType",y);x.vg("anychart.scope.XhrIo",Ca);var Ta={};x.vg("anychart.WMode",Ta);x.O(Ta,"WINDOW","window");x.O(Ta,"TRANSPARENT","transparent");x.O(Ta,"OPAQUE","opaque");var Ua={};x.vg("anychart.RenderingType",Ua);x.O(Ua,"FLASH_ONLY","flash");x.O(Ua,"SVG_ONLY","svg");x.O(Ua,"FLASH_PREFERRED","flashPreferred");x.O(Ua,"SVG_PREFERRED","svgPreferred");
function z(a,b,c){c&&(this.id=c);this.swfFile=z.swfFile;this.preloaderSWFFile=z.preloaderSWFFile;this.width=z.width;this.height=z.height;this.enableFirefoxPrintPreviewFix=z.enableFirefoxPrintPreviewFix;this.enabledChartEvents=z.enabledChartEvents;this.enabledChartMouseEvents=z.enabledChartMouseEvents;this.renderingType=z.renderingType;this.watermark=z.watermark;this.messages.preloaderInit=z.messages.preloaderInit;this.messages.preloaderLoading=z.messages.preloaderLoading;this.messages.init=z.messages.init;
this.messages.loadingConfig=z.messages.loadingConfig;this.messages.loadingResources=z.messages.loadingResources;this.messages.loadingTemplates=z.messages.loadingTemplates;this.messages.noData=z.messages.noData;this.messages.waitingForData=z.messages.waitingForData;a&&(this.swfFile=a);b&&(this.preloaderSWFFile=b);this.Md={};z.PL(this)}x.vg("AnyChart",z);z.VERSION="6.0.11 (build #36916)";x.O(z,"VERSION",z.VERSION);z.width=550;x.O(z,"width",z.width);z.height=400;x.O(z,"height",z.height);z.ZD="flash";
x.O(z,"renderingType",z.ZD);z.AB=i;x.O(z,"enabledChartEvents",z.AB);z.BB=n;x.O(z,"enabledChartMouseEvents",z.BB);z.UE=l;x.O(z,"swfFile",z.UE);z.WD=l;x.O(z,"preloaderSWFFile",z.WD);z.Hh=i;x.O(z,"enableFirefoxPrintPreviewFix",z.Hh);z.prototype.id=l;x.O(z.prototype,"id",z.prototype.id);z.Es=[];z.bL=function(){return z.Es&&0<z.YG()};z.YG=function(){return z.Es.length};z.RG=function(){return z.Es};z.Yp={};z.SG=function(){return z.Yp};z.prototype.ZD=l;x.O(z.prototype,"renderingType",z.prototype.ZD);
z.prototype.ja=l;z.prototype.$j=n;z.prototype.uM=l;x.O(z.prototype,"xmlFile",z.prototype.uM);z.prototype.qL=l;x.O(z.prototype,"jsonFile",z.prototype.qL);z.prototype.tM=l;x.O(z.prototype,"xmlData",z.prototype.tM);z.prototype.pL=l;x.O(z.prototype,"jsonData",z.prototype.pL);z.prototype.width=l;x.O(z.prototype,"width",z.prototype.width);z.prototype.height=l;x.O(z.prototype,"height",z.prototype.height);z.prototype.qM=l;x.O(z.prototype,"watermark",z.prototype.qM);z.prototype.UE=l;
x.O(z.prototype,"swfFile",z.prototype.UE);z.prototype.WD=l;x.O(z.prototype,"preloaderSWFFile",z.prototype.WD);z.prototype.Hh=i;x.O(z.prototype,"enableFirefoxPrintPreviewFix",z.prototype.Hh);z.prototype.pM=l;x.O(z.prototype,"wMode",z.prototype.pM);z.prototype.AB=i;x.O(z.prototype,"enabledChartEvents",z.prototype.AB);z.prototype.BB=n;x.O(z.prototype,"enabledChartMouseEvents",z.prototype.BB);z.prototype.Md=l;z.prototype.bgColor="#FFFFFF";x.O(z.prototype,"bgColor",z.prototype.bgColor);
z.prototype.oM=i;x.O(z.prototype,"visible",z.prototype.oM);z.prototype.show=function(){this.visible=i;this.ja.show()};x.O(z.prototype,"show",z.prototype.show);z.prototype.Gt=function(){this.visible=n;this.ja.Gt()};x.O(z.prototype,"hide",z.prototype.Gt);z.J={};z.J.wC=function(a){return"undefined"!=typeof a};z.J.push=function(a,b){a[a.length]=b};var Va=navigator&&navigator.userAgent?navigator.userAgent.toLowerCase():l,Wa=navigator&&navigator.platform?navigator.platform.toLowerCase():l;z.platform={};
x.O(z,"platform",z.platform);z.platform.Bo=Wa?/win/.test(Wa):/win/.test(Va);x.O(z.platform,"isWin",z.platform.Bo);z.platform.lL=!z.platform.Bo&&(Wa?/mac/.test(Wa):/mac/.test(Va));x.O(z.platform,"isMac",z.platform.lL);z.platform.hH="undefined"!=typeof document.getElementById&&"undefined"!=typeof document.getElementsByTagName&&"undefiend"!=typeof document.createElement;x.O(z.platform,"hasDom",z.platform.hH);z.platform.xJ=/webkit/.test(Va)?parseFloat(Va.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):n;
x.O(z.platform,"webKit",z.platform.xJ);z.platform.Tq=/msie/.test(Va);x.O(z.platform,"isIE",z.platform.Tq);z.platform.zH=/firefox/.test(Va);x.O(z.platform,"isFirefox",z.platform.zH);z.platform.protocol="https:"==location.protocol?"https:":"http:";x.O(z.platform,"protocol",z.platform.protocol);
z.AH=function(){z.platform.Ph=[0,0,0];var a;if(navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"]){if((a=navigator.plugins["Shockwave Flash"].description)&&(!navigator.mimeTypes||!navigator.mimeTypes[["application/x-shockwave-flash"]]||navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))a=a.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),z.platform.Ph[0]=parseInt(a.replace(/^(.*)\..*$/,"$1"),10),z.platform.Ph[1]=parseInt(a.replace(/^.*\.(.*)\s.*$/,"$1"),10),z.platform.Ph[2]=
/[a-zA-Z]/.test(a)?parseInt(a.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if("undefined"!=typeof window.ActiveXObject)try{var b=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(b&&(a=b.GetVariable("$version")))a=a.split(" ")[1].split(","),z.platform.Ph=[parseInt(a[0],10),parseInt(a[1],10),parseInt(a[2],10)]}catch(c){}return z.platform.Ph!=l&&9<=Number(z.platform.Ph[0])};x.O(z,"isFlashPlayerValidVersion",z.AH);z.platform.xC=z.AH();x.O(z.platform,"hasRequiredVersion",z.platform.xC);
z.platform.Ph=z.platform.Ph;x.O(z.platform,"flashPlayerVersion",z.platform.Ph);z.platform.hk=z.platform.xC&&z.platform.Tq&&z.platform.Bo;x.O(z.platform,"needFormFix",z.platform.hk);z.platform.hk&&(z.platform.hk=9==Number(z.platform.Ph[0]),z.platform.hk=z.platform.hk&&0==Number(z.platform.Ph[1]),z.platform.hk=z.platform.hk&&115>Number(z.platform.Ph[2]));z.EB=[];z.ML=function(a){x.Jx(a)&&z.EB.push(a)};x.O(z,"ready",z.ML);
z.sL=function(a){if(a==l||a==h)a=z.EK();var a=a+"AnyChartHTML5.js",b=new Ca;b.jF=i;x.r.Na(b,"complete",z.vI,l,z);x.r.Na(b,["error","abort"],z.uI,l,z);b.send(a,"GET",l,"anychart.com")};x.O(z,"loadHTML5Engine",z.sL);z.vI=function(a){var a=a.target,b;try{b=a.tc?a.tc.responseText:""}catch(c){b=""}eval(b.toString());b=z.EB.length;for(var e=0;e<b;e++)z.EB[e]();z.jK(a)};z.uI=function(){d(Error("Can not find AnyChart html5 engine in JS folder."))};
z.jK=function(a){x.r.Pb(a,"complete",z.vI,l,z);x.r.Pb(a,["error","abort"],z.uI,l,z)};z.EK=function(){for(var a=x.global.document.getElementsByTagName("script"),b=a.length-1;b>=0;--b){var c=a[b].src,e=c.lastIndexOf("?"),e=e==-1?c.length:e,c=c.substr(0,e),f=c.split("/"),f=f[f.length-1].toLowerCase(),g=f.length;if(f.indexOf("anychart")!=-1&&f.substr(g-3,3)==".js")return c.substr(0,e-g)}return l};z.J.attachEvent=function(a,b,c){a.attachEvent(b,c);z.J.push(z.J.fP,[a,b,c])};
z.J.NJ=function(a,b){if(z.J.wC(window.addEventListener))window.addEventListener(a,b,n);else if(z.J.wC(document.addEventListener))document.addEventListener(a,b,n);else if(z.J.wC(window.attachEvent))z.J.attachEvent(window,"on"+a,b);else if(typeof window["on"+a]=="function"){var c=window["on"+a];window["on"+a]=function(){c();b()}}else window["on"+a]=b};x.vg("AnyChart.utils.addGlobalEventListener",z.J.NJ);z.J.Qq=n;z.J.qB=[];z.J.MJ=function(a){z.J.Qq?a():z.J.qB.push(a)};
z.J.mq=function(){if(!z.J.Qq){try{var a=document.getElementsByTagName("body")[0].appendChild(document.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}z.J.Qq=i;for(var a=z.J.qB.length,c=0;c<a;c++)z.J.qB[c]()}};
z.J.OL=function(){if(z.platform.hH){typeof document.readyState!="undefined"&&(document.readyState=="complete"||document.getElementsByTagName("body")[0]||document.body)&&z.J.mq();if(!z.J.Qq){document.addEventListener&&document.addEventListener("DOMContentLoaded",z.J.mq,n);if(z.platform.Tq&&z.platform.Bo){document.attachEvent("onreadystatechange",function(){if(document.readyState=="complete"){document.detachEvent("onreadystatechange",arguments.callee);z.J.mq()}});window==top&&function(){if(!z.J.Qq){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}z.J.mq()}}()}z.platform.xJ&&function(){z.J.Qq||(/loaded|complete/.test(document.readyState)?z.J.mq():setTimeout(arguments.callee,0))}();x.r.Na(window,"load",z.J.mq)}}};z.J.OL();z.dispatchEvent=function(a,b){z.PF(a)&&b!=l&&z.Yp[a].dispatchEvent(b)};x.O(z,"dispatchEvent",z.dispatchEvent);
function Ya(a){switch(a.renderingType){case "svg":return new window.anychart.render.svg.SVGRenderer;case "flash":return new La;default:case "flashPreferred":return z.platform.hasRequiredVersion?new La:new window.anychart.render.svg.SVGRenderer;case "svgPreferred":return window.SVGAngle!=h?new window.anychart.render.svg.SVGRenderer:new La}}z.PL=function(a){a.id=a.id==h?"__AnyChart___"+z.Es.length:a.id;z.Yp[a.id]=a;z.Es.push(a)};z.PF=function(a){return a&&z.Yp&&z.Yp[a]};
z.GK=function(a){return z.PF(a)?z.Yp[a]:l};x.O(z,"getChartById",z.GK);z.rK=function(a,b){z.iq(a,b)};x.O(z,"disposeFlashObject",z.rK);z.iq=function(a,b){a.iq(a,b)};x.O(z,"disposeVisual",z.iq);z.prototype.iq=function(a,b){this.ja.iq(a,b)};z.J.Te={};x.vg("AnyChart.utils.JSConverter",z.J.Te);z.J.Te.QC=function(a){a=typeof a;return a=="string"||a=="number"||a=="boolean"};x.O(z.J.Te,"isAttribute",z.J.Te.QC);z.J.Te.isArray=function(a){return typeof a!="string"&&typeof a.length!="undefined"};
x.O(z.J.Te,"isArray",z.J.Te.isArray);z.J.Te.$J=function(a){return z.J.Te.WA("anychart",a)};x.O(z.J.Te,"convert",z.J.Te.$J);
z.J.Te.WA=function(a,b){var c,e,f="<"+a;if(typeof b.functionName!="undefined"){b["function"]=b.functionName;delete b.functionName}for(c in b)c!="format"&&c!="text"&&c!="custom_attribute_value"&&c!="attr"&&z.J.Te.QC(b[c])&&(f=f+(" "+c+'="'+b[c]+'"'));f=f+">";for(c in b)if(c=="arg"&&z.J.Te.isArray(b[c])){var g=b[c];for(e=0;e<g.length;e++)f=f+("<arg><![CDATA["+g[e]+"]]\></arg>")}else if(c=="custom_attribute_value"||c=="attr")f=f+("<![CDATA["+b[c]+"]]\>");else if(c=="format"||c=="text")f=f+("<"+c+"><![CDATA["+
b[c]+"]]\></"+c+">");else if(z.J.Te.isArray(b[c])){g=b[c];for(e=0;e<g.length;e++)f=f+z.J.Te.WA(c,g[e])}else z.J.Te.QC(b[c])||(f=f+z.J.Te.WA(c,b[c]));return f+("</"+a+">")};z.messages={};z.messages.preloaderInit=" ";z.messages.preloaderLoading="Loading... ";z.messages.init="Initializing...";z.messages.loadingConfig="Loading config...";z.messages.loadingResources="Loading resources...";z.messages.loadingTemplates="Loading templates...";z.messages.noData="No Data";z.messages.waitingForData="Waiting for data...";
z.watermark=l;z.prototype.xL={};x.O(z.prototype,"messages",z.prototype.xL);z.prototype.messages.preloaderInit=l;z.prototype.messages.preloaderLoading=l;z.prototype.messages.init=l;z.prototype.messages.loadingConfig=l;z.prototype.messages.loadingResources=l;z.prototype.messages.loadingTemplates=l;z.prototype.messages.noData=l;z.prototype.messages.waitingForData=l;z.prototype.addEventListener=function(a,b){this.Md[a]==l&&(this.Md[a]=[]);this.Md[a].push(b)};x.O(z.prototype,"addEventListener",z.prototype.addEventListener);
z.prototype.removeEventListener=function(a,b){if(!(this.Md==l||this.Md[a]==l)){for(var c=-1,e=0;e<this.Md[a].length;e++)if(this.Md[a][e]==b){c=e;break}c!=-1&&this.Md[a].splice(c,1)}};x.O(z.prototype,"removeEventListener",z.prototype.removeEventListener);z.prototype.dispatchEvent=function(a){if(!(a==l||a.type==l)){a.type=="create"?this.ja.rI():a.type=="draw"&&this.ja.sI();a.target=this;if(!(this.Md==l||this.Md[a.type]==l))for(var b=this.Md[a.type].length,c=0;c<b;c++)this.Md[a.type][c](a)}};
x.O(z.prototype,"dispatchEvent",z.prototype.dispatchEvent);z.prototype.Jn=function(){return this.ja.Jn()};x.O(z.prototype,"canWrite",z.prototype.Jn);z.prototype.write=function(a){this.ja=Ya(this);this.ja.mo(this);if(this.Jn()){if(a==h){a="__chart_generated_container__"+this.id;document.write('<div id="'+a+'"></div>')}var b=this;z.J.MJ(function(){typeof a=="string"?Za(b,document.getElementById(a)):Za(b,a)})}};x.O(z.prototype,"write",z.prototype.write);
function Za(a,b){a.$j=a.ja.write(b);a.$j&&a.As()&&(a.xmlFile!=l?a.oi(a.xmlFile):a.jsonFile!=l?a.kn(a.jsonFile):a.xmlData!=l?a.Vu(a.xmlData):a.jsonData!=l&&a.jj(a.jsonData))}z.prototype.As=function(){return this.ja.As()};x.O(z.prototype,"canSetConfigAfterWrite",z.prototype.As);z.prototype.Fz=function(){this.ja.Fz()};x.O(z.prototype,"updatePrintForFirefox",z.prototype.Fz);z.prototype.sp=function(a,b){this.width=a;this.height=b;this.ja.sp(a,b)};x.O(z.prototype,"setSize",z.prototype.sp);
x.vg("AnyChart.prototype.resize",z.prototype.sp);z.prototype.remove=function(){this.ja.remove()};x.O(z.prototype,"remove",z.prototype.remove);z.prototype.clear=function(){this.ja.clear()};x.O(z.prototype,"clear",z.prototype.clear);z.prototype.refresh=function(){this.ja.refresh()};x.O(z.prototype,"refresh",z.prototype.refresh);z.prototype.Sr=function(a,b){this.ja.Sr(a,b)};x.O(z.prototype,"updateData",z.prototype.Sr);z.prototype.Vy=function(a){this.ja.Vy(a)};x.O(z.prototype,"setLoading",z.prototype.Vy);
z.prototype.Yw=function(){return this.ja.Yw()};x.O(z.prototype,"getInformation",z.prototype.Yw);z.prototype.oi=function(a){this.xmlFile=a;this.$j&&this.ja.oi(a)};x.O(z.prototype,"setXMLFile",z.prototype.oi);z.prototype.uh=function(a){this.xmlData=""+a;this.$j&&this.ja.uh(this.xmlData)};x.O(z.prototype,"setXMLData",z.prototype.uh);z.prototype.Vu=function(a){this.$j&&this.ja.Vu(a)};x.O(z.prototype,"setXMLDataFromString",z.prototype.Vu);z.prototype.cz=function(a){this.$j&&this.ja.cz(a)};
x.O(z.prototype,"setXMLDataFromURL",z.prototype.cz);z.prototype.tp=function(a,b){this.ja.tp(a,b)};x.O(z.prototype,"setViewXMLFile",z.prototype.tp);z.prototype.Zy=function(a,b){this.ja.Zy(a,b)};x.O(z.prototype,"setViewData",z.prototype.Zy);z.prototype.kn=function(a){this.jsonFile=a;this.$j&&this.ja.kn(a)};x.O(z.prototype,"setJSONFile",z.prototype.kn);z.prototype.jj=function(a){this.jsonData=a;this.$j&&this.ja.jj(this.jsonData)};x.O(z.prototype,"setJSONData",z.prototype.jj);
x.vg("AnyChart.prototype.setJSData",z.prototype.jj);z.prototype.setData=function(a){if(a!=l){for(var b=""+a;b.charAt(0)==" "&&b.length>0;)b=b.substr(1);if(b.charAt(0)=="<"){this.xmlData=""+a;this.$j&&this.ja.uh(this.xmlData)}else{this.jsonData=a;this.$j&&this.ja.jj(this.jsonData)}}};x.O(z.prototype,"setData",z.prototype.setData);z.prototype.$c=function(a,b){this.ja.$c(a,b)};x.O(z.prototype,"addPoint",z.prototype.$c);z.prototype.xj=function(a,b,c){this.ja.xj(a,b,c)};x.O(z.prototype,"addPointAt",z.prototype.xj);
z.prototype.nk=function(a,b){this.ja.nk(a,b)};x.O(z.prototype,"removePoint",z.prototype.nk);z.prototype.Bk=function(a,b,c){this.ja.Bk(a,b,c)};x.O(z.prototype,"updatePoint",z.prototype.Bk);z.prototype.uj=function(a,b,c){this.ja.uj(a,b,c)};x.O(z.prototype,"updatePointData",z.prototype.uj);z.prototype.Vj=function(a,b,c){this.ja.Vj(a,b,c)};x.O(z.prototype,"highlightPoint",z.prototype.Vj);z.prototype.fj=function(a,b,c){this.ja.fj(a,b,c)};x.O(z.prototype,"selectPoint",z.prototype.fj);
z.prototype.Ez=function(a,b,c,e){this.ja.Ez(a,b,c,e)};x.O(z.prototype,"updatePointWithAnimation",z.prototype.Ez);z.prototype.nz=function(){this.ja.nz()};x.O(z.prototype,"startPointsAnimation",z.prototype.nz);z.prototype.yj=function(a){this.ja.yj(a)};x.O(z.prototype,"addSeries",z.prototype.yj);z.prototype.zj=function(a,b){this.ja.zj(a,b)};x.O(z.prototype,"addSeriesAt",z.prototype.zj);z.prototype.ok=function(a){this.ja.ok(a)};x.O(z.prototype,"removeSeries",z.prototype.ok);
z.prototype.Ck=function(a,b){this.ja.Ck(a,b)};x.O(z.prototype,"updateSeries",z.prototype.Ck);z.prototype.uk=function(a,b){this.ja.uk(a,b)};x.O(z.prototype,"showSeries",z.prototype.uk);z.prototype.Wj=function(a,b){this.ja.Wj(a,b)};x.O(z.prototype,"highlightSeries",z.prototype.Wj);z.prototype.Uj=function(a,b){this.ja.Uj(a,b)};x.O(z.prototype,"highlightCategory",z.prototype.Uj);z.prototype.jz=function(a,b){this.ja.jz(a,b)};x.O(z.prototype,"showAxisMarker",z.prototype.jz);
z.prototype.rk=function(a,b){this.ja.rk(a,b)};x.O(z.prototype,"setPlotCustomAttribute",z.prototype.rk);z.prototype.js=function(a,b,c){this.ja.js(a,b,c)};x.O(z.prototype,"view_setPlotCustomAttribute",z.prototype.js);z.prototype.as=function(a,b){this.ja.as(a,b)};x.O(z.prototype,"view_addSeries",z.prototype.as);z.prototype.hs=function(a,b){this.ja.hs(a,b)};x.O(z.prototype,"view_removeSeries",z.prototype.hs);z.prototype.bs=function(a,b,c){this.ja.bs(a,b,c)};x.O(z.prototype,"view_addSeriesAt",z.prototype.bs);
z.prototype.ms=function(a,b,c){this.ja.ms(a,b,c)};x.O(z.prototype,"view_updateSeries",z.prototype.ms);z.prototype.ks=function(a,b,c){this.ja.ks(a,b,c)};x.O(z.prototype,"view_showSeries",z.prototype.ks);z.prototype.Zr=function(a,b,c){this.ja.Zr(a,b,c)};x.O(z.prototype,"view_addPoint",z.prototype.Zr);z.prototype.$r=function(a,b,c,e){this.ja.$r(a,b,c,e)};x.O(z.prototype,"view_addPointAt",z.prototype.$r);z.prototype.gs=function(a,b,c){this.ja.gs(a,b,c)};x.O(z.prototype,"view_removePoint",z.prototype.gs);
z.prototype.ls=function(a,b,c,e){this.ja.ls(a,b,c,e)};x.O(z.prototype,"view_updatePoint",z.prototype.ls);z.prototype.Oz=function(a){this.ja.Oz(a)};x.O(z.prototype,"view_clear",z.prototype.Oz);z.prototype.fs=function(a){this.ja.fs(a)};x.O(z.prototype,"view_refresh",z.prototype.fs);z.prototype.es=function(a,b,c){this.ja.es(a,b,c)};x.O(z.prototype,"view_highlightSeries",z.prototype.es);z.prototype.ds=function(a,b,c,e){this.ja.ds(a,b,c,e)};x.O(z.prototype,"view_highlightPoint",z.prototype.ds);
z.prototype.cs=function(a,b,c){this.ja.cs(a,b,c)};x.O(z.prototype,"view_highlightCategory",z.prototype.cs);z.prototype.is=function(a,b,c,e){this.ja.is(a,b,c,e)};x.O(z.prototype,"view_selectPoint",z.prototype.is);z.prototype.Ur=function(a,b,c,e){this.ja.Ur(a,b,c,e)};x.O(z.prototype,"updateViewPointData",z.prototype.Ur);z.prototype.Bq=function(a,b){if(a==l||a==h)a=NaN;if(b==l||b==h)b=NaN;return this.ja.Bq(a,b)};x.O(z.prototype,"getPNG",z.prototype.Bq);x.vg("AnyChart.prototype.getPNGImage",z.prototype.Bq);
z.prototype.kx=function(a,b){if(a==l||a==h)a=NaN;if(b==l||b==h)b=NaN;return this.ja.kx(a,b)};x.O(z.prototype,"getPDF",z.prototype.kx);z.prototype.zy=function(){this.ja.zy()};x.O(z.prototype,"printChart",z.prototype.zy);z.prototype.Ly=function(a,b){if(a==l||a==h)a=NaN;if(b==l||b==h)b=NaN;this.ja.Ly(a,b)};x.O(z.prototype,"saveAsImage",z.prototype.Ly);z.prototype.My=function(a,b){if(a==l||a==h)a=NaN;if(b==l||b==h)b=NaN;this.ja.My(a,b)};x.O(z.prototype,"saveAsPDF",z.prototype.My);z.prototype.Ny=function(a){this.ja.Ny(a)};
x.O(z.prototype,"scrollXTo",z.prototype.Ny);z.prototype.Oy=function(a){this.ja.Oy(a)};x.O(z.prototype,"scrollYTo",z.prototype.Oy);z.prototype.scrollTo=function(a,b){this.ja.scrollTo(a,b)};x.O(z.prototype,"scrollTo",z.prototype.scrollTo);z.prototype.Lz=function(a,b){this.ja.Lz(a,b)};x.O(z.prototype,"viewScrollXTo",z.prototype.Lz);z.prototype.Mz=function(a,b){this.ja.Mz(a,b)};x.O(z.prototype,"viewScrollYTo",z.prototype.Mz);z.prototype.px=function(){return this.ja.px()};
x.O(z.prototype,"getXScrollInfo",z.prototype.px);z.prototype.qx=function(){return this.ja.qx()};x.O(z.prototype,"getYScrollInfo",z.prototype.qx);z.prototype.nx=function(a){return this.ja.nx(a)};x.O(z.prototype,"getViewXScrollInfo",z.prototype.nx);z.prototype.ox=function(a){return this.ja.ox(a)};x.O(z.prototype,"getViewYScrollInfo",z.prototype.ox);z.prototype.dz=function(a){this.ja.dz(a)};x.O(z.prototype,"setXZoom",z.prototype.dz);z.prototype.ez=function(a){this.ja.ez(a)};
x.O(z.prototype,"setYZoom",z.prototype.ez);z.prototype.fz=function(a,b){this.ja.fz(a,b)};x.O(z.prototype,"setZoom",z.prototype.fz);z.prototype.$y=function(a,b){this.ja.$y(a,b)};x.O(z.prototype,"setViewXZoom",z.prototype.$y);z.prototype.az=function(a,b){this.ja.az(a,b)};x.O(z.prototype,"setViewYZoom",z.prototype.az);z.prototype.bz=function(a,b,c){this.ja.bz(a,b,c)};x.O(z.prototype,"setViewZoom",z.prototype.bz);z.prototype.Lv=function(){this.ja.Lv()};x.O(z.prototype,"animate",z.prototype.Lv);
z.prototype.Lc=function(a){return this.ja.Lc(a)};x.O(z.prototype,"getSVG",z.prototype.Lc);})()
